siddhi-io/siddhi

modules/siddhi-extensions/string/src/main/java/org/wso2/siddhi/extension/string/EqualsIgnoreCaseFunctionExtension.java
modules/siddhi-extensions/string/src/main/resources/str.siddhiext
modules/siddhi-extensions/string/src/test/java/org/wso2/siddhi/extension/string/EqualsIgnoreCaseFunctionExtensionTestCase.java

Implemented str:equalsIgnoreCase(String, toAnotherString) string function which is similar to JAVA 
<public boolean equalsIgnoreCase(String anotherString)>
function

add more Test Cases and Apache Licence Text to EqualsIgnoreCaseFunctionExtension

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/ExecutionPlanRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/config/ExecutionPlanContext.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/callback/QueryCallback.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/StreamJunction.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/SingleStreamEntryValve.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/StreamCallback.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/stream/ExceptionHandlerTestCase.java

- https://issues.apache.org/jira/browse/EAGLE-41
- https://wso2.org/jira/browse/CEP-1411
We are running siddhi(v3.0.2) on storm, but found siddhi engine will throw RuntimeException and crash when receive an invalid input.What's more, any invalid input will block the whole topology, also for siddhi are using async callback with disruptor, we are not able to catch these exception by try-catch. The Unit Test here https://github.com/haoch/siddhi/blob/ce5ffcf9368f63d8af2072c4666b8c3e938a93be/modules/siddhi-core/src/test/java/org/wso2/siddhi/core/stream/ExceptionHandlerTestCase.java#L127-L141 proves the disruptor thread crashes while caught with exception, which means that the problem has not been resolved completely
The root cause is that Siddhi is relying on …

CEP-1411 Support to customize exception handler for disruptor in siddhi when creating ExecutionPlanRuntime

---

modules/siddhi-extensions/string/src/main/java/org/wso2/siddhi/extension/string/SplitFunctionExtension.java
modules/siddhi-extensions/string/src/main/resources/str.siddhiext
modules/siddhi-extensions/string/src/test/java/org/wso2/siddhi/extension/string/SplitFunctionExtensionTestCase.java

This can be used as follows in Siddhi:
str:split(sourceString, splitCharacter, returnedOutputPosition)
This will split the sourceString by splitCharacter and return the string in the index given by returnedOutputPosition​ ​

Split Function for String extension 

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/collection/operator/SimpleOperator.java

Fix for [1], Indexed InMemory table joins won't allow compound conditional statements with ON operator. Please review and merge.
[1] https://wso2.org/jira/browse/CEP-1491

Fixed for CEP-1491

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/join/JoinTestCase.java

Fix for [1] & [2], Current implementation of TimeWindowProcessor does not comply with Operator implementations. Fixing only the test case, since Siddhi does not allow "within"  with "join" operator. Please review and merge.
[1] https://wso2.org/jira/browse/CEP-1413
[2] https://wso2.org/jira/browse/CEP-1452

Fixed CEP-1413

---

modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/rdbms/RDBMSEventTableConstants.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/rdbms/RDBMSOperatorParser.java
modules/siddhi-extensions/event-table/src/main/resources/rdbms-table-config.xml

- Added `IS NULL` support for RDBMS tables
- Added `NOT` operator support for RDBMS tables (i.e. `NOT(value==20)`, `NOT IS NULL`)

Fixed `IS NULL` syntax in RDBMS

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/ExternalTimeWindowProcessor.java

You can only see AttributeAggregator.processAdd but not AttributeAggregator.processRemove in external time sliding window. The issue is caused by we don't reset expiredEventChunk before removing expired events, and the lastReturned event does not have next event.

External time sliding window does not remove expired events

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/ExecutionPlanRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/Event.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/InputEventHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/PassThroughSourceMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/PassThroughSinkMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/SinkMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-extensions/input-mappers/text-input-mapper/src/main/java/org/wso2/siddhi/extension/input/mapper/text/TextSourceMapper.java
modules/siddhi-extensions/input-mappers/xml-input-mapper/src/main/java/org/wso2/siddhi/extension/input/mapper/xml/XmlSourceMapper.java
modules/siddhi-extensions/input-transports/kafka-input-transport/src/main/java/org/wso2/siddhi/extension/input/transport/kafka/KafkaConsumerThread.java
modules/siddhi-extensions/input-transports/kafka-input-transport/src/test/java/org/wso2/siddhi/extension/input/transport/kafka/KafkaSourceTestCase.java
modules/siddhi-extensions/output-mappers/text-output-mapper/src/main/java/org/wso2/siddhi/extension/output/mapper/text/TextSinkMapper.java
modules/siddhi-extensions/output-transports/kafka-output-transport/src/main/java/org/wso2/siddhi/extension/output/transport/kafka/KafkaSink.java

This commit implements the high availability for a multi-node Siddhi deployment
using Kafka transport as the communication medium between nodes.
eg:
kafka -> Siddhi1 -> kafka -> Siddhi2 -> output
Feature is tested using a test case, which creates above shown scenario
and executes a siddhi file in a distributed manner (1 query is deployed
in Siddhi1 and the other query is deployed in Siddhi2).

High availability in a multi-node Siddhi deployment

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/executor/function/FunctionExecutor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/executor/function/ScriptFunctionExecutor.java

This fixes a bug during a clone operation which is invoked during when processing data. Stack trace for the bug is below. Tested this with the fix and it works fine.
result = {StackTraceElement[30]@10489} 
0 = {StackTraceElement@10253} "java.lang.Class.getConstructor0(Class.java:3082)"
1 = {StackTraceElement@10254} "java.lang.Class.newInstance(Class.java:412)"
2 = {StackTraceElement@10255} "org.wso2.siddhi.core.executor.function.FunctionExecutor.cloneExecutor(FunctionExecutor.java:56)"
3 = {StackTraceElement@10256} "org.wso2.siddhi.core.query.selector.attribute.aggregator.AttributeAggregator.cloneAggregator(AttributeAggregator.java:58)"
4 = {StackTraceElement@10257} "org.wso2.siddhi.core.query.selector.attribute.processor.executor.GroupByAggregationAttributeExecutor.execute(GroupByAggregat …

Fix for ScriptFunctionExecutor to enable cloning

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/LogicalPostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/LogicalPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/StreamPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StateInputStreamParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/LogicalPatternTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/sequence/SequenceTestCase.java

Fixed the following:
for A or B select
within not respected with logical
every not respected with sequence
logical pattern following every

Fix sequence and pattern issue with every and within

---

modules/siddhi-doc-gen/src/main/resources/templates/documentation.md.ftl
modules/siddhi-doc-gen/src/main/resources/templates/extensions.md.ftl
modules/siddhi-doc-gen/src/main/resources/templates/index.md.ftl

This PR contains the following
- Removing ".md" endings from urls
- Fixing the table of contents in documentation page

Bug Fix : Remove ".md" from template links

---

modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/Constants.java
modules/siddhi-doc-gen/src/main/resources/templates/documentation.md.ftl

This PR contains the following.
- Changing the top level heading of documentation page to "API Docs"
- Changing the mkdocs configuration file key to "API Docs"

Doc Gen plugin - Update templates

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java

Siddhi extensions won't work in android platform.
The issue is that the regex engine used in Android is an ICU engine (http://userguide.icu-project.org/strings/regexp)  that is different from Java one, and both { and } that represent literal open/close curly braces must be escaped in ICU regex patterns.

Fix Regex bug in android

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java

Currently siddhi only identifies option parameter values defined only with a place holder. 
But it does not identifies option parameters as dynamic if the place holder is placed in the middle of a string.
For example :
`@sink(type='file', uri={{symbol}}'`
In this case, uri will be identified as a dynamic option.
`@sink(type='file', uri='/abc/{{symbol}}.json`
In this case, uri will not be taken as a dynamic parameter even we have registered as a supported dynamic option.
This is a fix for that issue.

adding fix to accept options as dynamic when placeholder placed within a stirng

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/AvgAttributeAggregator.java

Variable 'count' is of type 'long'. Hence all casting should be to 'long' instead of 'int' when the "Count" object is retrieved from the 'state' map.

Changed invalid cast from long to int

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/config/ConfigReader.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/config/InMemoryConfigReader.java

add a method 'getAllconfigs' to the ConfigReader interface and implemented that method in InMemoryConfigReader in a way that returns a map which contains all configuration for the corresponding 'keyPrefix'.

add method 'getAllconfigs' to the ConfigReader interface.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentLogicalPostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentLogicalPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentStreamPostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentStreamPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/LogicalPostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/LogicalPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/StreamPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StateInputStreamParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/absent/AbsentPatternTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/absent/AbsentWithEveryPatternTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/absent/EveryAbsentPatternTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/absent/LogicalAbsentPatternTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/sequence/SequenceTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/sequence/absent/AbsentSequenceTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/sequence/absent/AbsentWithEverySequenceTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/sequence/absent/EveryAbsentSequenceTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/sequence/absent/LogicalAbsentSequenceTestCase.java
modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/execution/query/input/state/AbsentStreamStateElement.java
modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/execution/query/input/state/LogicalStateElement.java
modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/execution/query/input/state/State.java
modules/siddhi-query-api/src/test/java/org/wso2/siddhi/query/api/PatternQueryTestCase.java
modules/siddhi-query-compiler/src/main/antlr4/org/wso2/siddhi/query/compiler/SiddhiQL.g4
modules/siddhi-query-compiler/src/main/java/org/wso2/siddhi/query/compiler/internal/SiddhiQLBaseVisitorImpl.java
modules/siddhi-query-compiler/src/test/java/org/wso2/siddhi/query/test/AbsentPatternTestCase.java

This PR contains the implementation of Siddhi pattern to detect the absence of events.
**Sample cases:**
- `A -> not B for 1sec`
- `A -> not B and C`
- `A -> (not B and C) within 1sec`
- `A -> (not B for 1sec  and C) within 2sec`
- `not A for 1sec -> B`
- `not A and B -> C`
- `every ( not B and  A)  -> C`
- `every ( not B for 1sec)  -> C`
- `A -> not B  for 1 sec and not C for 1 sec`
- `not A  for 1 sec and not B for 1 sec -> C`
- `A -> not B   for 1 sec or not C for 1 sec`
- `not A  for 1 sec or not B for 1 sec -> C`
- `A -> not B for 1 sec or C`
- `not A for 1 sec or B -> C`

Add pattern to detect events that are not arrived

---

modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/commons/metadata/ExtensionType.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/ExtensionsIndexGenerationMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/MarkdownDocumentationGenerationMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/MkdocsGitHubPagesDeployMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/Constants.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/DocumentationUtils.java
modules/siddhi-doc-gen/src/main/resources/templates/documentation.md.ftl
modules/siddhi-doc-gen/src/main/resources/templates/extensions.md.ftl
modules/siddhi-doc-gen/src/main/resources/templates/index.md.ftl
modules/siddhi-doc-gen/src/main/resources/templates/utils.ftl

This PR contains the following
* Remove all  x.x.x-SNAPSHOT when doing release perform
* Support for adding "## Features" heading in the homePageTemplate file which will be replaced by a list of API Doc extensions
* Support for adding "## Latest API Docs" heading in the homePageTemplate file which will be replaced by the main API Docs version
* Add "namespace:" in syntax of Function, Attribute Aggregator, Window, Stream Function & Stream Processor
* Change from heading to normal text with same style for Sytex, Query Parameters, Example etc (Other than for the API Names)
* Link to type function doc in Siddhi Doc from the "type" of "Name(type)" heading of each API Name.
* Add syntax for Script

Update siddhi-doc-gen plugin templates

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentLogicalPostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentLogicalPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentStreamPostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentStreamPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/LogicalPostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StateInputStreamParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/absent/AbsentPatternTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/absent/LogicalAbsentPatternTestCase.java

I didn't override the cloneProcessor methods which caused to an error with partitions. This PR fixes that bug. The ReentrantLock of AbsentLogicalPreStateProcessor is created in the setPartnerStatePreProcessor method to cooperate with partitioning.

Fix error in partitioning the absent pattern processor

---

modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/MkdocsGitHubPagesDeployMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/Constants.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/DocumentationUtils.java
modules/siddhi-doc-gen/src/main/resources/templates/headings-update.md.ftl

This PR contains the following changes
* Remove the mkdocs gh-deploy command execution
* Add mkdocs build command execution to build the documentation
* Add git commands to deploy the documentation to github pages

Siddhi Doc Gen Plugin - change the mkdocs gh-deploy to a manual git push

---

modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/annotation/Annotation.java

Previously the method misses adding a comma(",")  before the first annotation inside source or sink configuration when trying to retrieve stream definition as a string.

Modifying Siddhi Query API Annotation

---

README.md
docs/index.md
mkdocs.yml
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/TestUtil.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/absent/AbsentPatternTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/absent/AbsentWithEveryPatternTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/absent/EveryAbsentPatternTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/absent/LogicalAbsentPatternTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/sequence/absent/AbsentSequenceTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/sequence/absent/AbsentWithEverySequenceTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/sequence/absent/EveryAbsentSequenceTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/sequence/absent/LogicalAbsentSequenceTestCase.java

This PR contains the fix for the check-style issue caused by my last PR #510.
I have also changed the `TestCallback` interface name according to your feedback and used this class in all absent pattern & sequence test classes.

Fix checkstyle issue in TestUtil and renamed TestCallback

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/partition/PartitionRuntime.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/partition/PartitionTestCase.java

- Register snapshotable service in PartitionRuntime's init().
- Removed try/catch blocks for catching DuplicateAnnotationException since it's caught earlier by SiddhiCompiler.
- Added test cases for org.wso2.siddhi.core.query.partition

Improving code coverage of org.wso2.siddhi.core.query.partition

---

modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/ExtensionsIndexGenerationMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/MarkdownDocumentationGenerationMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/MkdocsGitHubPagesDeployMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/Constants.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/DocumentationUtils.java
modules/siddhi-doc-gen/src/main/resources/templates/headings-update.md.ftl

Re-implementing #519 with the following changes to it
* Retrieving SCM username and password from the environment variables.
* Changing back to the initial branch the build was running in, rather than the master branch, after running the "deploy-mkdocs-github-pages" goal.

Siddhi Doc Gen Plugin - Re-implement "change the mkdocs gh-deploy to a manual git push"

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/Source.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/Sink.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/SinkHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java

> So that the states of SinkHandler and SourceHandler can be persisted and restored
> This feature can be used in SP 2 node HA Sync States
> Implement Snapshotable interface, register with snapshot service

Make SinkHandler and SourceHandler Snapshotable

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java

> To expose SiddhiApp statistics details in SiddhiAppRuntime.
> Add a method to get SiddhiApp statistics state.
Add a method to get SiddhApp matric prefix.

Adding methods to expose SiddhiApp statistics details

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PersistenceTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

> To fix jenkins build failure due to persistence test cases
> Make test cases run sequentially. Remove unnecessary increment of count variable.

Fix build failure on persistence test cases

---

modules/siddhi-query-compiler/src/main/antlr4/org/wso2/siddhi/query/compiler/SiddhiQL.g4
modules/siddhi-query-compiler/src/main/java/org/wso2/siddhi/query/compiler/internal/SiddhiQLBaseVisitorImpl.java

This PR removes unused output event types from grammar file

Removing unused output event types from grammar file

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/transport/Option.java

To fix possible Class cast exception
Use String.ValueOf instead of direct casting
JDK 1.8.0

fix class cast exception

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/filter/FilterProcessor.java

> When a boolean type attribute is used as Siddhi filter expression there is a possibility of 'NullPointerException'. So this simple change is done to avoid it.

Fixed 'NullPointerException' issue in FilterProcessor.

---

docs/documentation/siddhi-4.0.md

Adding missing timeLength as an inbuilt window
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests 
N/A
N/A
N/A
N/A
N/A
N/A
N/A

Adding timeLength as an inbuilt window

---

modules/siddhi-extensions/time/src/main/java/org/wso2/siddhi/extension/time/ExtractAttributesFunctionExtension.java
modules/siddhi-extensions/time/src/test/java/org/wso2/siddhi/extension/time/ExtractAttributesFunctionExtensionTestCase.java

extension.
> Siddhi function time:extract() uses the current value of the default locale of the JVM, because of that there is no way to extract date information for given locale.
> Introducing an optional locale parameter to Siddhi time extract.
<int>  time: extract (<string> unit ,<string>  dateValue, <string> dataFormat, <string> locale)

Introducing an optional locale parameter to Siddhi time extract

---

docs/documentation/siddhi-4.0.md

Changing the sentence at line number 893 to give the correct meaning
From "Following is a Siddhi App the controls the temperature regulators if they are not already `on` for all the rooms with a room temperature greater than 30 degrees.  "
to 
"Following is a Siddhi App that controls the temperature regulators if they are not already `on` for all the rooms with a room temperature greater than 30 degrees.  
"

Changing the sentence at line number 893 to give the correct meaning

---

docs/documentation/siddhi-4.0.md

| `<event reference>` | This allows you toadd a reference to the the matching event so that it can be accessed later for further processing. |
to
| `<event reference>` | This allows you to add a reference to the the matching event so that it can be accessed later for further processing. |

Added a missing space in line number 1143

---

docs/documentation/siddhi-4.0.md

github code mark down is not properly working in mkdocs when spaces are present infront. This PR fix that issue by removing those spaces

Fix markdown issues in mkdocs

---

docs/documentation/siddhi-4.0.md

Changed the URL for output-event-types 
from http://127.0.0.1:8000/documentation/siddhi-4.0/#output-event-types  
to #output-event-types 
in Table under Insert and Delete
To fix two broken links
Changed the URL for output-event-types 
from http://127.0.0.1:8000/documentation/siddhi-4.0/#output-event-types  
to #output-event-types 
in Table under Insert and Delete

Fixed 2 Broken Links

---

modules/siddhi-extensions/time/src/test/java/org/wso2/siddhi/extension/time/ExtractAttributesFunctionExtensionTestCase.java

> Fixing time extract assert test failure due to JVM time zone issue.
> Initialize the calendar with same local and use the calendar when asset the siddhi output.

Fixing time extract assert test failure due to JVM time zone issue.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiManager.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/exception/CannotRestoreSiddhiAppStateException.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/persistence/PersistenceService.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PersistenceTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/partition/PartitionTestCase.java

> Null pointer thrown when restoring a siddhi app when its content changed after state is persisted
> Fix issue null pointer being thrown when siddhi app content changes and restoring from an old revision
> Catch throwable at snapshot service level and thrown a checked exception.
> Refactor test cases to handle the thrown exception

Fix restoring state of updated siddhi app

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/Sink.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/SinkHandler.java

> Passing sinkHandlerCallback down so that in when implementing SinkHandler, callback can be used to send publish events
> Pass the sinkHandlerCallback instance to the abstract init method in SinkHandler

Pass SinkHandlerCallback down

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/holder/IndexEventHolder.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/holder/PrimaryKeyReferenceHolder.java

> Fix Issue #677 
> Make InMemoryTable be able to be persisted
> Made PrimaryKeyReferenceHolder and IndexEventHolder Serializable
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
>  N/A
>  N/A
>  N/A
> Ubuntu 16.04
>  N/A

Make InMemoryTable be able to be persisted

---

docs/api/latest.md
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/stream/MetaStreamEvent.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/ExpressionParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/MatcherParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/OutputParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/PartitionParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/QueryParserHelper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/window/Window.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/stream/event/EventTestCase.java

> Fixing the MetaEvent Optimization method doesn't properly optimize output data
> by stoping adding duplicate values

Fixing issue #675 not optimizing output data

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java

> Check for null when unregistering recordTableHandler becuase InMemoryTables handler is null
> Check if handler is null before unregistering

Bug fix. Appruntime shutdown not working when InMemoryTable used with HA

---

modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/definition/AbstractDefinition.java
modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/definition/AggregationDefinition.java
modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/definition/TableDefinition.java
modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/definition/WindowDefinition.java

Removing annotations array list from annotation definition class

Removing annotations array list from annotation definition class and overloading tostring method in definitions

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/PartitionParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/partition/PartitionTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/partition/PatternPartitionTestCase.java

> Currently partitions can be defined with nonexisting streams, and they are simply omitted. This might cause user errors. This fix is to throw an error when on existing steams are defined in the partitions. 
> Improve the user experience and helping the user to write proper Siddhi queries. 
> Adding validations to partitioned streams within the partition definition.

Adding validation to partition streams.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/RecreateInMemoryData.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/AggregationTestCase.java

1) Correct recreate in-memory data logic by keeping reference to next latest event prior to filtering out events. Otherwise, issues may occur if number of events equals 0, when filtered based on latest event.
2) Improve tests

Improvements to Incremental Aggregation

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/partition/PartitionRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SiddhiAppParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PersistenceTestCase.java

> Elements of partitions are created dynamically hence restoring of state is not functioning properly
> Persist partition keys in snapshot and restore the partition runtimes first so that all elements of partitions are created before restoring all other elements 
> Register all partition runtimes to snapshot service under common name - "partition" so that keys of all partitions are saved in the snapshot
> When restoring, restore the partition runtimes first so that the according to the partition keys relevant elements are created.
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other …

Fix partition snapshot and restore

---

modules/siddhi-query-compiler/src/test/java/org/wso2/siddhi/query/test/DefineStreamTestCase.java

> Change test case to expect SiddhiParserException instead of DuplicateAttributeException
> Change expectedException in test case
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Change expectedException in DefineStreamTestCase

---

modules/siddhi-extensions/time/src/test/java/org/wso2/siddhi/extension/time/ExtractAttributesFunctionExtensionTestCase.java
modules/siddhi-extensions/time/src/test/java/org/wso2/siddhi/extension/time/TimestampInMillisecondsFunctionExtensionTestCase.java

> This will fix the test cases issue in the time component of the siddhi extensions.
> This will fix the test cases issue in the time component of the siddhi extensions.
> Remove the hardcoded values in the test cases and use Java Util calender to get the time according to the time-zone
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
> NA

Fix test time test cases for different time zones

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/store/StoreQueryTableTestCase.java

Add test cases for getting output attributes of StoreQuery
Add test cases for getting output attributes of StoreQuery
Add test cases for getting output attributes of StoreQuery
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
NA

Add test cases for getting output attributes of StoreQuery

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/config/SiddhiAppContext.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiConstants.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SiddhiAppParser.java

Provide option for users to control transport channel creation. Currently only Kafka sources will support it. 
Siddhi App level annotation 'transportChannelCreationEnabled' is introduced. At AppParser annotation will be extracted and set to SiddhiAppContext so that it can be used across sources. Default value is true
> JDK 1.8

Add transport channel creation property to SiddhiAppContext

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java

Fix issue in restoring siddhi app from non-existing revision. Currently, when we are trying to restore siddhiApp from a non-existing revision, it will not return any exception. 
Fix issue in restoring siddhi app from non-existing revision.
Throw a new exception when there is no revision related to the requested siddhi app.
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
NA

Fix issue in restoring siddhi app from non existing revision

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/QueryRuntime.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/ratelimit/TimeOutputRateLimitTestCase.java

Resolves issue https://github.com/wso2/product-sp/issues/624
Rate limiters were not started for partition runtimes. This fix starts rate limiters after cloning new PartitionRuntime.
JDK 1.8

Fix time based output rate limiter for partitions

---

docs/documentation/siddhi-4.0.md

Fix typo.
Fix typo.
Replace `camalCase` with `camelCase`
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A

Fix `camalCase`s

---

modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/execution/query/input/store/AggregationInputStore.java
modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/execution/query/selection/OrderByAttribute.java
modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/execution/query/selection/Selector.java

> Siddhi Store API fails to identify updated queries used with OrderBy and ON keywords. Identifying the updated queries.
> Fixes [#753](https://github.com/wso2/product-sp/issues/753) and [#743](https://github.com/wso2/product-sp/issues/743)
> Override equals methods in OrderByAttribute and AggregationInputStore

Update equals methods in OrderByAttribute and AggregationInputStore

---

docs/api/latest.md
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/BaseIncrementalValueStore.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalDataAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalExecutor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalExternalTimestampDataAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/executor/incremental/IncrementalShouldUpdateFunctionExecutor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiExtensionLoader.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/AggregationTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/LatestAggregationTestCase.java

$subject. Fixes https://github.com/wso2/siddhi/issues/899
The latest aggregator will be called to all attributes other than group by attributes and calculations.
This will store an additional information "AGG_LAST_EVENT_TIMESTAMP" to the aggregation inner tables to track the last arrived events timestamp. Thus latest value can be calculated from the above column.
N/A.. as this is a bug fix

Adding latest aggregator support for Incremental Aggregations

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalDataPurging.java

eventChunk will be cleaned before adding a new purging event with purging time and the current timestamp. So that the issue which reported in https://github.com/wso2/product-sp/issues/835 get fixed

Fix for the issue https://github.com/wso2/product-sp/issues/835

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/DelayWindowProcessor.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/window/DelayWindowTestCase.java

The purpose of this PR is to add a new window feature to the siddhi stream processing. A siddhi developer may need to capture the events that has arrived and hold them for a specified time period before processing. In the current window implementations there is no direct implementation for this.
This new window feature - delay window, will allow to process events received from streams after delaying them for defined time period.
Implement new delay window processor class.
A courier company wants to detect their non-delivered packages within a predefined period of time. Events arriving from arrival stream can be delayed and compared with the events from delivery stream to check the timely delivery of packages.
N/A
N/A
N/A
N/A
- Unit tests 
Class - 100%
Method - 61%
Line - 74%
- Followed …

Siddhi delay window

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/window/DelayWindowTestCase.java

This commit fix the delay window test case failing in Jenkins build. 
N/A 
Increase the waiting time for the events to be processed.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
https://github.com/wso2/siddhi/pull/926
N/A
N/A

Change delay window test cases waiting time

---

docs/documentation/siddhi-4.0.md

Add delay window in to documentation

Add delay window in to documentation

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/Table.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/transport/BackoffRetryCounter.java
pom.xml

> The purpose of this PR is to improve the table connection exception handling mechanism. As per the  current implementation events are drop while the connection retrying, as in like when a Siddhi app consume messages from a Kafka source and insert each message into RDBMS table, and if there is a connection issue occurs at the database, siddhi app will drop the event at RDBMS event table when it's trying to perform add operation and then continue the messages consuming at Kafka source.
Other Fixes:
- Fix the BackoffRetryCounter loop count
- Remove unused dependency versions
> The Siddhi app execution flow busy-wait until the table connection recovered.
> Improve the table connection retrying mechanism by introducing a new function call busy wait, which is wait for the thread notification …

 Improve the table connection retrying mechanism

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/BatchWindowProcessor.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/window/BatchWindowTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

> The purpose of this PR is to fix the window.batch expired event while loop issue, earlier this loop has not terminated once the stream event chunks iteration finished. Also, added unit test cases to validate the functionality of the window.batch extension.
> Add window.batch test cases and fix an issue in expired events process loop
> Change the events expired do...while loop condition and add test cases.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> BatchWindowTestCase.java  53%
> N/A
> N/A
> N/A
> JDK 8
> N/A

Add window.batch test cases and fix an issue in expired events process loop

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/Source.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/transport/InMemoryTransportTestCase.java

Fixes https://github.com/wso2/siddhi/issues/932
Calling a scheduler for backoff rather than calling connectionWithRetry(This resets the backoff counter)
N/A
- Unit tests - Passes All
Changed as per functionality change - If onError is called, retrial is not called immediately. Has a 5 sec delay.

Fix connection retry w/o backoff if connection callback error is called

---

docs/documentation/siddhi-4.0.md

> Add a missing link to the Siddhi Query Guide
> Added a link to the Batch window.

This links the Batch window documentation to the Siddhi Query Guide.

---

docs/documentation/siddhi-4.0.md

> To link the session window content to the siddhi query guide
> The session window was added to the list of window types specified in the guide.

This links the Session window documentation to the Siddhi Query Guide.

---

docs/documentation/siddhi-4.0.md
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/Aggregation2TestCase.java

$subject. Fixes https://github.com/wso2/siddhi/issues/977
Clean documentation
Enable users to override partitionById system param is set as true
Introduce enable element in @PartitionById annotation
Changed herewith
- Unit tests Attached
- Integration tests - Ran the ones available in siddhi-store-rdbms

 [Distributed Aggregation] Fix issue of not able to overide when partitionById system param is set as true

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/Aggregation2TestCase.java

$subject. The above test case is failing due to the identified issue https://github.com/wso2/siddhi/issues/985
N/A

Stabilize build by disable incrementalStreamProcessorTest49 testcase

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalDataPurging.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalExecutor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java

> Improve the throughput of Aggregations by validating weather debugging is enabled before debugging information is logged. #992 
> Change aggregation metric name to Aggregations from Windows (Fix for issue #993)

Improve throughput of aggregations and change aggregation metric name

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalExecutor.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/Aggregation2TestCase.java

$subject. Fixes incorrect AGG_TIMESTAMP value if the one step down granularity is not completed once. For instance in higher granularity such as the day when queried after starting aggregation for few minutes (before the hour ends). This ONLY happens when the bucket ends (Year: January)
Fixes https://github.com/wso2/siddhi/issues/985
N/A

Fix incorrect setting of start time of executors at initialization

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/InputEventHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/InputEventHandlerCallback.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/PassThroughSourceHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/Source.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceEventListener.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceSyncCallback.java

> The purpose of this PR is to adding functionality to sync the event source transport properties between the HA nodes. 
This is the siddhi fix required for the issue: https://github.com/wso2/product-sp/issues/909
> With the fix, a source can produce TransportSyncProperties and pass them to SourceHandler, which can synchronise the information with the passive node. Here the receiving SourceHandler can update the sources through SourceSyncCallback.
> Update the source handlers and mappers with the source transport sync properties.
> NA
> NA
> NA
> NA
> NA
> NA
- Unit tests 
- Confirmed that this PR doesn't …

Fix syncing event sources in an HA environment

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/InputEventHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/InputEventHandlerCallback.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/PassThroughSourceHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/Source.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceEventListener.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceSyncCallback.java

Fix syncing event sources in an HA environment
In HA scenarios allow passive node push sources to be synced with active node

Allow transport sync properties to be sent via event

---

docs/documentation/siddhi-4.0.md
docs/extensions.md
modules/siddhi-core/siddhi-core-doc-gen/pom.xml

> Add hyperlinks to access siddhi-io-prometheus through the documentation
>  Providing Siddhi documentation with the links for siddhi-io-prometheus

Added extension links for siddhi-io-prometheus

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalDataAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java

> Fixes [SP-912](https://github.com/wso2/product-sp/issues/912)
> Fixes #1010 
> Fixes concurrent modification exception in incremental data aggregation. 
> Fix the slowness in searching snapshotables. 
> Maintain a clone of BaseIncrementalValueStoreGroupByMap while aggregating in-memory data.
> When initializing siddhi executors (function/aggregation etc) a snapshotable is added to that.
This add snapsohtable operation is slow when there is a higher number of executors being created. Using a map instead of a list to store snapshots improves the slowness while searching snapshotables. 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
- Ran …

Fixes concurrent modification exception in incremental data aggregation and improves slowness in searching snapshotables. 

---

modules/siddhi-service/src/gen/java/org/wso2/siddhi/service/api/ApiException.java
modules/siddhi-service/src/gen/java/org/wso2/siddhi/service/api/ApiOriginFilter.java
modules/siddhi-service/src/gen/java/org/wso2/siddhi/service/api/ApiResponseMessage.java
modules/siddhi-service/src/gen/java/org/wso2/siddhi/service/api/NotFoundException.java
modules/siddhi-service/src/gen/java/org/wso2/siddhi/service/api/SiddhiApi.java
modules/siddhi-service/src/gen/java/org/wso2/siddhi/service/api/SiddhiApiService.java
modules/siddhi-service/src/gen/java/org/wso2/siddhi/service/api/StringUtil.java
modules/siddhi-service/src/gen/java/org/wso2/siddhi/service/model/Error.java
modules/siddhi-service/src/gen/java/org/wso2/siddhi/service/model/Success.java
modules/siddhi-service/src/main/java/org/wso2/siddhi/service/impl/SiddhiApiServiceImpl.java

> Since javax package has been removed from JDK 11

Remove javax.annotations added while code generation from swagger

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/streamfunction/AttributeStreamFunction.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/streamfunction/StreamFunctionTestCase.java
modules/siddhi-query-compiler/src/main/antlr4/org/wso2/siddhi/query/compiler/SiddhiQL.g4

This allows us to define and use streams as
```
define stream `$InputStream` (`56$2theta` double, rho double);
```

Supporting non standard IDs using ``

---

findbugs-exclude.xml

> When building with Java 11, we encounter a SE_TRANSIENT_FIELD_NOT_RESTORED findbug in class SnapshotableStreamEventQueue. We do not encounter the same while building with Java 8. 
> Support Siddhi building with both Java 8 and Java 11.
> Add a findbugs suppression in findbugs-exclude.xml for SE_TRANSIENT_FIELD_NOT_RESTORED in SnapshotableStreamEventQueue class.
> N/A
> N/A
> N/A
> N/A
>  N/A
> N/A
- N/A 
> N/A
> N/A
> N/A
> OracleJDK 11, OracleJDK 8, OpenJDK 11
> N/A

Add findbugs suppression to support JAVA 11

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/AggregationParser.java

SHARD_ID of the distributed aggregation tables are not added as one of the primary key, only when distributed aggregation is enabled by the 'partitionById' siddhi property
Fix https://github.com/siddhi-io/siddhi/issues/1073
Update local variable properly
N/A

Fix SHARD_ID not added as one of the primarykey coloumn

---

modules/siddhi-core/src/test/java/io/siddhi/core/transport/InMemoryTransportTestCase.java

Make InMemoryTransportTestCase testcases run sequentially in Jenkins.

Make InMemoryTransportTestCase testcases run sequentially in Jenkins.

---

docs/api/latest.md
modules/siddhi-core/src/test/java/io/siddhi/core/query/function/InstanceOfFunctionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/function/MaximumFunctionExtensionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/function/MinimumFunctionExtensionTestCase.java

> This PR will remove the Junit usages from the test cases and avoid failures when updating the testng dependency.

Remove junit usages from test cases

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java

Fix, query results from event time stamp based aggregations intermittently being doubled. This is because of using the same executors to do the final calculations.
This can only happen when the executors have not been refreshed(aggregation time expired) when doing the final calculations to smooth out the out of order events.
Solve intermittent test case failures, Fixes https://github.com/siddhi-io/siddhi/issues/1110 and fixes https://github.com/siddhi-io/siddhi/issues/1081.
Fix the aggregation values getting doubled when querying in the aggregations (based on external timestamp)
Clone expression executors used for aggregations before calculating the out of order records
N/A
- …

[Inc. Aggregations] Clone executors for out of order event smoothing

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java

Fix, query results from event time stamp based aggregations intermittently being doubled. This is because of using the same executors to do the final calculations.
This can only happen when the executors have not been refreshed(aggregation time expired) when doing the final calculations to smooth out the out of order events.
Solve intermittent test case failures, Fixes https://github.com/siddhi-io/siddhi/issues/1110 and fixes https://github.com/siddhi-io/siddhi/issues/1081.
Fix the aggregation values getting doubled when querying in the aggregations (based on external timestamp)
Clone expression executors used for aggregations before calculating the out of order records
N/A
- …

[Inc. Aggregations] Clone executors for out of order event smoothing(4.4.x)

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/config/SiddhiAppContext.java

> $subject
> Make metrics to be disabled in the siddhi app context initialization
> Make metrics level to OFF as it was initially done https://github.com/siddhi-io/siddhi/blob/v4.4.9/modules/siddhi-core/src/main/java/org/wso2/siddhi/core/config/SiddhiAppContext.java#L50

Fix continuous metrics logs printed in editor mode

---

pom.xml

> This PR removes the Siddhi mkdocs generation and deployment for 4.4.x to avoid documentation update when there is a release in Siddhi 4.4.x because it deploys outdated content.

Remove mkdocs generation & deployment for Siddhi 4.4.x

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/CollectionExpressionParser.java

$subject. Fixes https://github.com/siddhi-io/siddhi/issues/1186, In memory Event table primary key lookups throws NPE 
N/A

Fix incorrect parsing of join compile condition

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/ServiceDeploymentInfo.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/Source.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/InMemorySink.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/LogSink.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/Sink.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/distributed/DistributedTransport.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/MultiClientDistributedSink.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/SingleClientDistributedSink.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/InMemoryTransportTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/MultiClientDistributedSinkTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/SingleClientDistributedTransportTestCases.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/TestDepInMemorySink.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/TestDepInMemorySource.java

> This introduces an API change to source and sink extensions, and allow them to give port, protocol and security-related information to the deployment, such as Kubernetes.
> To make siddhi to work natively with Kubernetes. 
> Allow Siddhi source and sink to give info to the deployment to expose the services.

 Add support to expose service information for deployment

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalExecutor.java

$subject
To solve OOM when multiple find queries are called.
N/A

Clean group by resources from snapshotable services when refreshing reading executors

---

docs/documentation/siddhi-5.x/user-guide-5.x.md

> Previous app name example-siddhi-deployment made the reader confused. So, change that name to monitor-app.
> Remove confusions.
> Change kubernetes section of the documentation accordingly.
> minikube version: v0.33.1

Change app name to monitor-app

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalExecutor.java

$subject , 
Fixes, exceptions in Aggregation DB writes not being logged from Siddhi 4.5.1 introduced by https://github.com/siddhi-io/siddhi/pull/1197
Fixes https://github.com/siddhi-io/siddhi/issues/1246
Log the exceptions thrown in Aggregation DB writes
Submit DB write tasks to Executor Service as execute
N/A

Change Aggregation db writes as task execute

---

modules/siddhi-core/src/main/java/io/siddhi/core/table/holder/IndexEventHolder.java

Caught NPE exception while trying to insertUpdate with conditions.
Gracefully delete non-exist index events.

Handle NPE while deleted index not exist in indexMap

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalDataPurging.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/RecreateInMemoryData.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiConstants.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java

$subject. Fix https://github.com/siddhi-io/siddhi/issues/1235
Make recreate in-memory logic efficient so as to not select entire data in the tables.
As mentioned in https://github.com/siddhi-io/siddhi/issues/1235
N/A
- Unit tests 
Added in https://github.com/siddhi-io/siddhi-store-rdbms/pull/159, as this feature needs a persistent DB for testing

Improve Aggregation Recreate Inmemory Data to be more efficient

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalAggregationProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalDataAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalExternalTimestampDataAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/RecreateInMemoryData.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/FindStoreQueryRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/Aggregation1TestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/AggregationFilterTestCase.java

Optimize distributed aggregation querying
Reduce memory consumption when distributed aggregations are queried.
Rather than loading ongoing aggregation regardless of shard ID to the memory, the needed data (Applying on condition, within the time period) is executed on the lower granularity tables. 
However, additional time filtering is done, so as to not pick duplicate data. 
For instance,  if the find query comes at 9.30 for hour granularity, within t1 and t2, 
If Processing on external timestamp,
1. Hour table lookup as before within t1 and t2
2. a) Minute's table lookup within t1 and t2 and AGG_TIMSTAMP> 9.00
b) Seconds table lookup within t1 and t2 and AGG_TIMESTAMP > 9.29
If processing on system timestamp, 
1. Normal hour table lookup
2. If hour ongoing aggregations start time falls …

[Incremental Aggregation] Optimise distributed aggregation querying

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalAggregationProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/RecreateInMemoryData.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/FindStoreQueryRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation1TestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation2TestCase.java

Optimize distributed aggregation querying
Reduce memory consumption when distributed aggregations are queried.
Rather than loading ongoing aggregation regardless of shard ID to the memory, the needed data (Applying on condition, within the time period) is executed on the lower granularity tables. 
However, additional time filtering is done, so as to not pick duplicate data. 
For instance,  if the find query comes at 9.30 for hour granularity, within t1 and t2, 
If Processing on external timestamp,
1. Hour table lookup as before within t1 and t2
2. a) Minute's table lookup within t1 and t2 and AGG_TIMSTAMP> 9.00
b) Seconds table lookup within t1 and t2 and AGG_TIMESTAMP > 9.29
If processing on system timestamp, 
1. Normal hour table lookup
2. If hour ongoing aggregations start time falls …

[5x][Incremental Aggregation] Optimise distributed aggregation querying

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/StoreQueryParser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/helper/QueryParserHelper.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/AggregationFilterTestCase.java

$subject
>   @info(name = 'query1') 
>   from inputStream as i join stockAggregation as s 
>   on i.symbol == s.symbol 
>   within "2017-06-** **:**:**" 
>   per \"seconds\" 
>   select AGG_TIMESTAMP, **i.symbol**, lastTradeValue, totalPrice 
>   order by AGG_TIMESTAMP 
>   insert all events into outputStream;
> 
N/A

Fix find error when join query with aggregation selects attributes from stream

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/Scheduler.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/Aggregation2TestCase.java

> When SiddhiRuntime is shut down, the scheduler services will also be shut down. In such a case, if one tries to submit a new task to the scheduler, it will throw an InterruptedException. Hence, such cases can be ignored.

Ignoring InterruptedException during a SiddhiRuntime shutdown

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationExpressionVisitor.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java

$subject, When reduction is for A and B, if one of the operands is based on incremental attributes, both conditions are not passed to the DB.
If there is no 'on' condition Compile condition passed to the table is formatted as, 
AGG_TIMESTAMP<t1 and AGG_TIMESTAMP>t2 and **true**, which is changed to drop the trailing true
N/A
Are added in https://github.com/siddhi-io/siddhi-store-rdbms as these optimizations are for physical DB's only
DB: H2, MySQL, MSSQL, Postgres, Oracle 11 XE, Oracle 12 SE

 Improve reduction of aggregation on condition

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/IndexOperator.java

It is the root cause of  CPU cost by getLastEvent while add/remove event in ComplexEventChunk
https://github.com/siddhi-io/siddhi/issues/1270
> Resolve https://github.com/siddhi-io/siddhi/issues/1270
> It is a bug when try to reset the updated stream events retrieved from find method, as in-memory table did not clone event, so if the next was not reset, it will cause problem.
> It is a simple fix.
> Fix bug for potential dead loop caused by in-memory table update. this only happen when update in-memory table not via primary key.
> N/A
- Unit tests 
> N/A
> N/A
- Confirmed that this PR doesn't commit any …

Fix StreamEvent,next reference leak when update in-memory table

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/Scheduler.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/snapshot/ByteSerializer.java

(cherry picked from commit 19f833f)
> $subject
> forcefully schedule the 1st timer event when changing from passive to active

Force schedule the timer events when changing to active state

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/ComplexEventChunk.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/collection/operator/IndexOperator.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/stream/event/ComplexEventChunkTestCase.java

cherry pick from 90499831217d827bf438bdd33c59f9ae7948abf7 and a7e4a38fef81b91a0404ac2c913c1aa973659313

Backport fix of eventChunk loop and StreamEvent.next() leak in in-memory

---

docs/documentation/siddhi-5.x/siddhi-as-a-kubernetes-microservice-5.x.md

> The kubernetes deployment section of the siddhi documentation did not contain the details about how to change the default siddhi-runner image in the siddhi-operator level. 
> Add details about the changing siddhi-runner docker image.
> We can change docker image in two levels (operator-level and CRD level). Thus add note sections to operator deployment subsection and siddhi app deployment subsection.

Add siddhi-runner image changing section to the k8s deployment

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationExpressionVisitor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java

$subject, When reduction is for A and B, if one of the operands is based on incremental attributes, both conditions are not passed to the DB.
If there is no 'on' condition Compile condition passed to the table is formatted as, 
AGG_TIMESTAMP<t1 and AGG_TIMESTAMP>t2 and **true**, which is changed to drop the trailing true
Branch 5xx: https://github.com/siddhi-io/siddhi/pull/1329
N/A
Are added in https://github.com/siddhi-io/siddhi-store-rdbms as these optimizations are for physical DB's only
DB: H2, MySQL, MSSQL, Postgres, …

Improve reduction of aggregation on condition(back ported from 5.x.x)

---

findbugs-exclude.xml
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/definition/StreamDefinition.java

> This getAttributeNameArray() method from the base implementation is called on every event occurrence where it iterates the attribute list and results in a hotstop when there is huge load of events. This should be optimised.
> Optimizing getAttributeNameArray() method to compute the attribute list only once when the stream definition changes and not on every call to remove the hotstop.
> Overriding the base implementation in the derived class to compute the attribute list only once when the stream definition changes and not on every event occurrence.

Performance Improvement for Stream Definition Attribute Array Name list retrieval

---

modules/siddhi-annotations/src/main/java/io/siddhi/annotation/processor/AbstractAnnotationProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/function/Pol2CartStreamFunctionProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/LossyFrequentWindowProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/SortWindowProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/validator/InputParameterValidator.java

> To make sure the docs are consistent and correct.
> Validate mandatory parameter mismatch between ParameterOverload and 'optional' annotation.
> Validate mandatory parameter mismatch in Extension annotations.

Validate mandatory parameter mismatch in annotation.

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/validator/InputParameterValidator.java
modules/siddhi-core/src/test/java/io/siddhi/core/window/DelayWindowTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/window/SessionWindowTestCase.java

> Fix the no param case when paramOverload annotation is in place
> Improve error messages for paramOverload annotation

ParamOverload annotation related improvements & bug fixes

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/SourceHandlerManager.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/helper/DefinitionParserHelper.java

This PR adds `sourceType` parameter to the `SourceHandler. generateSourceHandler()` method.

Add source type to source handler

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/StreamJunction.java
modules/siddhi-core/src/main/java/io/siddhi/core/table/holder/IndexEventHolder.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/function/InstanceOfFunctionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/function/MaximumFunctionExtensionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/stream/FaultStreamTestCase.java

Fix Siddhi Error Handlers not getting engaged #1414

---

modules/siddhi-core/src/main/java/io/siddhi/core/event/stream/MetaStreamEvent.java
modules/siddhi-core/src/main/java/io/siddhi/core/executor/MultiValueVariableFunctionExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiConstants.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/ExpressionParser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/InputStreamParser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/JoinInputStreamParser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/SingleInputStreamParser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/StateInputStreamParser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/persistence/util/IncrementalSnapshotInfo.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/persistence/util/PersistenceHelper.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/CountPatternTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/absent/LogicalAbsentPatternTestCase.java

> Currently there is no way of retrieving the all the events that are collected by the counting-pattern, currently we can only access the events via their indexes. 
> Fixes https://github.com/siddhi-io/siddhi/issues/1398
> When counting patterns are used such as `e1=StockStream<2:8>` and when they are referred without indexes such as `e1.price` it collects the price values from all the events in the counting pattern `e1` and produce it as a list. Since the list is not native to Siddhi the attribute will have `object` as its type.
> Support outputting the events collected in counting-pattern as a list 
> When a counting pattern is referred without indexes such as `e1.x` all the values of …

Support list of values as the output of counting-pattern 

---

findbugs-exclude.xml
modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/CountPatternTestCase.java
modules/siddhi-doc-gen/src/main/java/io/siddhi/doc/gen/core/freemarker/FormatDescriptionMethod.java
modules/siddhi-doc-gen/src/main/resources/templates/documentation.md.ftl

> Improve API documentation readability. This allows docs having 
```
multi 
line content 
```

Support API docs having multiline code segments.

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/TemplateBuilder.java

> Fix for https://github.com/siddhi-io/siddhi/issues/858 ...

Improve TemplateBuilder & remove Java MessageFormat dependency

---

modules/siddhi-core/src/main/java/io/siddhi/core/query/input/MultiProcessStreamReceiver.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/ProcessStreamReceiver.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/SingleProcessStreamReceiver.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/AbsentLogicalPreStateProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/AbsentStreamPreStateProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/CountPreStateProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/LogicalPreStateProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/PreStateProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/StreamPreStateProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/receiver/PatternMultiProcessStreamReceiver.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/receiver/PatternSingleProcessStreamReceiver.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/receiver/SequenceMultiProcessStreamReceiver.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/receiver/SequenceSingleProcessStreamReceiver.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/runtime/StreamInnerStateRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/StateInputStreamParser.java
modules/siddhi-core/src/test/java/io/siddhi/core/TestUtil.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/CountPatternTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/EveryPatternTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/LogicalPatternTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/absent/AbsentWithEveryPatternTestCase.java

> Removes duplicate events and supports patterns expiry.
> Fixes #1425
> Fixes #1182 
> Every pattern support for having multiple state elements with within

 Support pattern every containing multiple state elements with within

---

modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/LogStreamProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/TimeBatchWindowProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/InMemorySource.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/InMemorySink.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/window/TimeBatchWindowTestCase.java

> To effectively implement throttling use cases with alert suppression. 
> Also improve documentation of in-memory sink, in-memory source, and log stream processor. 
>  Fixes to TimeBatchWindow to process events in a streaming manner, when it's enabled to send current events in streaming mode. This makes sure all having conditions are matched against the output, whereby allowing users to effectively implement throttling use cases with alert suppression.

 Fix TimeBatchWindow with streaming output, processing events in batches.

---

modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/ProcessingMode.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/TimeBatchWindowProcessor.java

>Fixes #1440
> Not compromise memory optimization.

Introduce RESET processing mode to preserve memory optimization. 

---

pom.xml

Reverts siddhi-io/siddhi#1432
> This is to avoid version compatibility issues (with dependencies) when creating the Siddhi distribution.

Revert "Bump slf4j.version from 1.7.12 to 1.7.26"

---

modules/siddhi-core/pom.xml
modules/siddhi-core/src/main/java/io/siddhi/core/exception/YAMLConfigManagerException.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/FileReader.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/config/ConfigManager.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/config/ConfigReader.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/config/YAMLConfigManager.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/config/YAMLConfigReader.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/config/model/Extension.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/config/model/ExtensionChildConfiguration.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/config/model/Reference.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/config/model/ReferenceChildConfiguration.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/config/model/RootConfiguration.java
modules/siddhi-core/src/test/java/io/siddhi/core/config/YAMLConfigManagerTestCase.java
modules/siddhi-core/src/test/resources/systemProperties.yaml
modules/siddhi-core/src/test/resources/testng.xml

$subject fixes https://github.com/siddhi-io/siddhi/issues/1445
To support YAML Config Manager for easy setting of system properties in SiddhiManager
As in f3c8ea2
Add support YAML Config Manager for easy setting of system properties in SiddhiManager through a YAML file
- Unit tests - Attached herewith
- Integration tests - N/A
1.8.0_191

Add YAMLConfigManager support

---

modules/siddhi-core/src/main/java/io/siddhi/core/SiddhiManager.java
modules/siddhi-core/src/test/java/io/siddhi/core/managment/SandboxTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/DeleteFromTableTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

Add `createSandboxSiddhiAppRuntime()` to SiddhiManager to create a SiddhiApp without sources, sinks, and stores. such that it can be used for testing. 
Fixes #1438

Add ability to create a Sandbox SiddhiAppRuntime for testing purposes. 

---

modules/siddhi-core/src/main/java/io/siddhi/core/executor/function/ConvertFunctionExecutor.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/function/ConvertFunctionTestCase.java

Improve convert to provide message & cause for Throwable

---

modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/AbsentLogicalPreStateProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/StreamPreStateProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/StreamJunction.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/InMemorySink.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/Sink.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/SinkMapper.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/distributed/DistributedTransport.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiAppRuntimeBuilder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/event/handler/StreamHandler.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/InMemoryBroker.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/absent/LogicalAbsentPatternTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/sequence/SequenceTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/stream/FaultStreamTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/InMemoryTransportTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/SinkOptionSinkMapper.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/TestAsyncInMemory.java
modules/siddhi-core/src/test/java/io/siddhi/core/window/WindowDefinitionTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

Purpose
> Support a way to retrieve the sink options and type at sink mapper. Fixes #1469
> Support error handling (log/wait/fault-stream) when event sinks publish data asynchronously. Fixes #1465 
> Fix time management in not pattern cases.
> #1469 Support a way to retrieve the sink options and type at sink mapper. 
> #1465 Support error handling (log/wait/fault-stream) when event sinks publish data asynchronously.

Add log/wait/fault-stream support for asynchronous event sinks

---

modules/siddhi-core/src/main/java/io/siddhi/core/table/record/ExpressionBuilder.java

Fix https://github.com/wso2/product-sp/issues/1039

Fix NPE when count() AttributeFunction is used

---

modules/siddhi-core/src/main/java/io/siddhi/core/partition/PartitionRuntimeImpl.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/EventHolderPasser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/PartitionParser.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/partition/PartitionTestCase2.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/IndexTableTestCase.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/util/AnnotationHelper.java

> To uniform the behavior of @index annotation of the table.
> For more information refer https://github.com/siddhi-io/siddhi/issues/1228
The behavior of `@index` annotation of the in-memory table is modified to accept only one index element per annotation. Through this, to use multiple indexes on the table multiple '@index(<index key>)' annotations should be defined per each index key.

Change the behavior of in-memory tables to support multiple '@index' annotations

---

modules/siddhi-core/src/main/java/io/siddhi/core/table/CacheTable.java
modules/siddhi-core/src/main/java/io/siddhi/core/table/InMemoryCompiledCondition.java
modules/siddhi-core/src/main/java/io/siddhi/core/table/InMemoryTable.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/CollectionOperator.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/EventChunkOperator.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/IndexOperator.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/MapOperator.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/Operator.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/OverwriteTableIndexOperator.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/OverwriteTableIndexOperatorForCache.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/SnapshotableEventQueueOperator.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/SiddhiAppParser.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/JoinTableTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/UpdateOrInsertTableTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/cache/CacheLFUTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/cache/CacheLRUTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/store/DeleteFromTestStoreTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/store/InTestStoreTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/store/InsertIntoTestStoreTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/store/JoinTestStoreTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/store/QueryAPITestCaseForTestStore.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/store/UpdateOrInsertTestStoreTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/store/UpdateTestStoreTestCase.java
modules/siddhi-core/src/test/resources/testng.xml
modules/siddhi-query-compiler/src/test/java/io/siddhi/query/test/DefineStreamTestCase.java

> Fix https://github.com/siddhi-io/siddhi/issues/1243

Fix update or insert in InMemoryTable using EventChuck

---

modules/siddhi-core/src/main/java/io/siddhi/core/table/CacheTable.java
modules/siddhi-core/src/main/java/io/siddhi/core/table/InMemoryTable.java
modules/siddhi-core/src/main/java/io/siddhi/core/table/record/AbstractQueryableRecordTable.java
modules/siddhi-core/src/main/java/io/siddhi/core/table/record/AbstractRecordTable.java
modules/siddhi-core/src/main/java/io/siddhi/core/table/record/ExpressionBuilder.java
modules/siddhi-core/src/main/java/io/siddhi/core/table/record/UpdateOrInsertReducer.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/UpdateOrInsertTableTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/stream/FaultStreamTestCase.java

> Support record tables and in-memory tables to correctly update or insert records.

Support tables to correctly update or insert records

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/Sink.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/distributed/DistributedTransport.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/MultiClientDistributedSink.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/SingleClientDistributedSink.java
modules/siddhi-core/src/test/java/io/siddhi/core/UnitTestAppender.java
modules/siddhi-core/src/test/java/io/siddhi/core/stream/FaultStreamTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/InMemoryTransportTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/MultiClientDistributedSinkTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/TestFailingInMemorySink.java

Improve reconnection logic when publish always throw connection unavailable exception.

Fix reconnection logic when publish() always throw connection unavailable exception

---

modules/siddhi-core/src/main/java/io/siddhi/core/config/SiddhiContext.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiExtensionLoader.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/AbstractExtensionHolder.java

>  Siddhi extensions are sometimes not picked by Siddhi Manager while creating Siddhi Runtime. This is because, the latter picked extensions by the ExtensionListenere will not be updated at the secondary extension map(extensionHolderMap).
> When an extension is picked/removed by extensionListener update it at the extensionHolderMap as well.

Update SiddhiExtensionHolder when OSGI listener updates bundles

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java

$subject, fixes https://github.com/siddhi-io/siddhi/issues/1537

Fix aggregation definition error logs

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiExtensionLoader.java

> Fixes https://github.com/siddhi-io/siddhi/issues/1540

Fix NPE being thrown intermittently while removing bundles in shutdown process

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/AttributeMapping.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/InputEventHandler.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/SourceEventListener.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/SourceMapper.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/AttributeConverter.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/InMemoryTransportTestCase.java

> Support mapping transport properties to any data type.
> Fixes https://github.com/siddhi-io/siddhi/issues/1557
> Currently, only String[] is supported as transport properties, with this fix Object[] can be passed as transport properties.
> This fix also supports converting the transport properties into the mapped attribute type.
> Support transport properties to be mapped to the attribute type.

Support mapping transport properties to any data type.

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/JoinInputStreamParser.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/JoinTableTestCase.java

Filter does not work when joining with table #1568

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/SourceMapper.java

Add fix for possible NPE

---

modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/SessionWindowProcessor.java
modules/siddhi-core/src/test/java/io/siddhi/core/window/SessionWindowTestCase.java

Improve session window documentation

---

modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/LogStreamProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/InputDistributor.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/InputManager.java
modules/siddhi-core/src/test/java/io/siddhi/core/managment/LogTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/managment/StartStopTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

> At times editor sends events to a wrong stream when worked with multiple event streams.

Fix Siddhi sending events to wrong stream when stopped and started.

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java

$subject fix https://github.com/siddhi-io/siddhi/issues/1591
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

Fix aggregation with persistence store AGG_TIMESTAMP not applying 

---

modules/siddhi-core/src/main/java/io/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/SiddhiAppRuntimeImpl.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/QueryRuntimeImpl.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/output/callback/QueryCallback.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/output/ratelimit/OutputRateLimiter.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/StreamJunction.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/CallbackTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/stream/CallbackTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

> Fixes https://github.com/siddhi-io/siddhi/issues/1590

Add support to remove stream and query callback dynamically.

---

findbugs-exclude.xml
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/event/stream/MetaStreamEvent.java
modules/siddhi-core/src/main/java/io/siddhi/core/event/stream/StreamEventCloner.java
modules/siddhi-core/src/main/java/io/siddhi/core/executor/EventVariableFunctionExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/executor/function/EventTimestampFunctionExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/BatchingWindowProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/ExpressionBatchWindowProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/ExpressionWindowProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/GroupingWindowProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/HopingWindowProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/SlidingWindowProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/ExpressionParser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/OnDemandQueryParser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/SingleInputStreamParser.java
modules/siddhi-core/src/main/java/io/siddhi/core/window/Window.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/function/FunctionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/window/ExpressionBatchWindowTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/window/ExpressionWindowTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/window/LengthBatchWindowTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/store/OnDemandQueryTableTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/stream/event/EventTestCase.java
modules/siddhi-core/src/test/resources/testng.xml
modules/siddhi-query-compiler/src/main/java/io/siddhi/query/compiler/SiddhiCompiler.java

> To hold values in the window only until the given expression is satisfied. The expression window expires the oldest events until the given expression is not satisfied, and the expressionBatch window expires all events as a batch when the given expression is not satisfied.  
> Here the expression should be passed as a string, as it is executed within the window. 
> Fixes https://github.com/siddhi-io/siddhi/issues/1596
> Support event expiry based on an expression.  
> Expression and ExpressionBatch window evaluates the events from the oldest (`first`) to the newest (`last`) and expires them if they do not satisfy the condition. 
>  E.g. 
```
from StockEventWindow#window.expression(
'sum(price) < 100 and eventTimestamp(last) - eventTimestamp(first) < 3000')
select symbol, sum(price) as …
```

Add expression and expressionBatch window

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/InMemorySource.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/trigger/TriggerTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/InMemoryTransportTestCase.java

Add latch mechanism to pause/resume in inmemory source

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/InputManager.java
pom.xml

Fixed issue-1600 by adding synchronized protection

Fixed issue-1600 add thread-safe protection to inputManager

---

pom.xml

> Effective from January 15, 2020, The Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS.
Source: https://support.sonatype.com/hc/en-us/articles/360041287334

Update central repo for secure communication

---

modules/siddhi-query-compiler/src/main/antlr4/io/siddhi/query/compiler/SiddhiQL.g4
modules/siddhi-query-compiler/src/main/java/io/siddhi/query/compiler/internal/SiddhiQLBaseVisitorImpl.java

Resolve #1624, making delete expression optional.
On delete statements, visitor implementation needs to first check whether there is an expression or not, since, according to the documentation, it is optional:
>When specifying the condition, the table attributes should always be referred with the table name, and and **when a condition is not defined, all the events in the table will be deleted**.
Before visiting the expression nodes, check whether expression has been specified in the first place.

Allow for unconditional deletes

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/SourceMapper.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiConstants.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/statistics/ReceivedEventCounter.java

Received Event Counter Log can be enabled from deployment.yaml for any source by providing the following configuration. 
>`enableLoggingEventCount: true`
`loggingDuration: 2`
By default this functionality is disabled and the default logging duration is 1 minute and duration has to provided in minutes. 
The sample output log will be as follows,
>`[2020-06-10 16:11:21,875]  INFO {io.siddhi.core.util.statistics.RecievedEventCounter} - Event received for Stream SweetProductionStream in siddhi App ReceiveHTTPinXMLFormatWithCustomMapping for last 1 minute(s): 60 .Total Events: 3636.`
- Confirmed that this PR doesn't commit any …

Add Received Event Count Logger functionality

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalDataAggregator.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutorsInitialiser.java
modules/siddhi-core/src/main/java/io/siddhi/core/executor/incremental/IncrementalAggregateBaseTimeFunctionExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/IncrementalTimeConverterUtil.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiConstants.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation2TestCase.java

The aggregation time period follows GMT timezone regardless of the user time zone before this feature. This may be inconvenient for users who want aggregations to happen according to their local timezones. This change makes time zone a configurable parameter in deployment.yaml as follows,
siddhi:
properties:
aggTimeZone: Asia/Singapore 
- 10 unit tests are written
> MacOS Catalina 10.15.3 Java 1.8.0_201

Make time zone configurable in aggregation

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/InputEventHandler.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/SourceMapper.java

> Add a counter to count and get total inputs got into the siddhi app after mapping.
> To count the dropped events count while mapping.
`((SourceMapper)sourceEventListener).getEventCount()`
> Introduce a new variable called `eventCount` in the `InputEventHandler` class.

Add a counter to count events after mapping

---

findbugs-exclude.xml
modules/siddhi-core/src/main/java/io/siddhi/core/util/error/handler/model/ErrorEntry.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/error/handler/store/ErrorStore.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/error/handler/util/ErrorHandlerUtils.java

> We use the [`ErrorEntry`](https://github.com/siddhi-io/siddhi/pull/1662/files#diff-f4fd3d1bde0e22f266cf9ce896a580a5R30) class to describe an error entry from the error store. 
- The event collected due to a error (eg: `Event`, `ComplexEvent` & etc) is [stored as a BLOB in the error store](https://github.com/siddhi-io/siddhi/pull/1662/files#diff-5641ac941cccafc2e4da4f6a9c813b00R164).
- When the error handler API's [`GET /error-handler/erroneous-events`](https://github.com/wso2/carbon-analytics/pull/1868/files#diff-86f8ec3bdca61bff7ca6d17e58b9a4cfR73) is invoked, the blob is [converted back to the appropriate event object](https://github.com/siddhi-io/siddhi/pull/1662/files#diff-5641ac941cccafc2e4da4f6a9c813b00R177), loaded as an `ErrorEntry` and will be sent as a JSON response.
- Since …

[Error Handler] Maintain events as byte[] in ErrorEntry

---

modules/siddhi-core/src/main/java/io/siddhi/core/exception/DatabaseConstraintViolationException.java
modules/siddhi-core/src/main/java/io/siddhi/core/exception/DatabaseRuntimeException.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/Sink.java
modules/siddhi-core/src/main/java/io/siddhi/core/table/Table.java
modules/siddhi-core/src/main/java/io/siddhi/core/table/record/AbstractRecordTable.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/error/handler/model/ReplayableTableRecord.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/error/handler/util/ErrorHandlerUtils.java

This PR adds support for catching and storing database violation errors such as 
* Primary Key Violation
* Not Null Violation
* Foreign Key Violation.
These errors will be caught and persisted in the error database with a JSON string containing all relevant information. This saved event can be replayed from the error store explorer. The detailed info dialog box looks as follows,
https://github.com/siddhi-io/siddhi/pull/1682
https://github.com/wso2/carbon-analytics/pull/1900
MacOS Catalina 10.15.6, JDK 1.8.0_201

Handle database errors for replaying

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/error/handler/store/ErrorStore.java

To fix high CPU consumption when siddhi error store is configured
Avoid high cpu consumption

Fix high cpu consumption

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/InputEventHandler.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/AbstractExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/AttributeAggregatorExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/DistributionStrategyExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/FunctionExecutorExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/IncrementalAttributeAggregatorExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/ScriptExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/SinkExecutorExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/SinkMapperExecutorExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/SourceExecutorExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/SourceMapperExecutorExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/StreamFunctionProcessorExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/StreamProcessorExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/TableExtensionHolder.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/holder/WindowProcessorExtensionHolder.java

- Resolves https://github.com/siddhi-io/siddhi/issues/1719. This fix is provided by @dnwick 
- Resolves https://github.com/siddhi-io/siddhi-map-json/issues/100
The trpProperties is set in the SourceMapper but it is removed by both SourceMapper and InputEventHandler.
For each event SourceMapper gets, it sets the trpProperties and hands over the event to InputEventHandler. After that removes the trpProperties.
For each event InputEventHandler gets, it removes the trpProperties too (it is unclear why it is doing this duplicate work).
Problem occurs when a batch of events comes to SourceMapper and it invokes the InputEventHandler multiple times (once for each event in the batch). Since InputEventHandler removes the trpProperties each time it gets an event; but the SourceMapper only sets it …

Fix extension loading issue in Windows environment

---

.travis.yml
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalDataPurger.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/persistedaggregation/config/PersistedAggregationResultsProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiConstants.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/main/resources/db-aggregation-config.xml

This PR will improve persisted aggregation implementation and Incremental Data Purging logic

Improve IncrementalDataPurger logic and Persisted Aggregation

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/TemplateBuilder.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/trigger/TriggerTestCase.java

- Resolves https://github.com/wso2/streaming-integrator/issues/228 (The testcase for this issue can be found in https://github.com/siddhi-io/siddhi-map-json/pull/104)
- Add testcase for https://github.com/siddhi-io/siddhi/issues/1542

Fix invalid json error given for a nested Json message

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java

> Improve incremental aggregation error handling

Improve incremental aggregation error handling

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/persistedaggregation/CudStreamProcessorQueueManager.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/persistedaggregation/PersistedIncrementalExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/persistedaggregation/QueuedCudStreamProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java

Allow persisted aggregations to run in a separate thread to stop the main thread getting hanged when the processing takes time
Improve logic

Improve persisted aggregations by introducing a queue implementation

---

modules/siddhi-annotations/src/main/java/io/siddhi/annotation/Extension.java
modules/siddhi-core/src/main/java/io/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/SiddhiAppRuntimeImpl.java
modules/siddhi-core/src/main/java/io/siddhi/core/config/SiddhiContext.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiExtensionLoader.java
modules/siddhi-core/src/test/java/io/siddhi/core/managment/WarningTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/util/TestStoreContainingInMemoryTable.java
modules/siddhi-query-compiler/pom.xml

$title. Currently `deprecated = true` is only used with doc gen. With this PR it will also give a runtime warning for such extensions.
```
@Extension(
name = "xxxxx",
deprecated = true,
namespace = "xxxxx",
description = "xxxxx",
examples = {
@Example(
xxxxx
)
}
)
```
n/a
n/a
- deprecated extensions will give a warning at the runtime.
n/a
- Unit tests added
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
n/a
n/a

Add runtime warnings for the deprecated extensions used in Siddhi Apps

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalDataPurger.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutorsInitialiser.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/persistedaggregation/PersistedIncrementalExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/IncrementalTimeConverterUtil.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiConstants.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java

> This PR will improve the aggregation executor initialization when using persisted aggregation.

Improve persisted aggregation and logs

---

modules/siddhi-query-compiler/src/main/antlr4/io/siddhi/query/compiler/SiddhiQL.g4

Add the following keywords under the `keyword` section of `SiddhiQL.g4` file.
```
FUNCTION
TRIGGER
OFFSET
SET
AT
IN
AGGREGATION
AGGREGATE
PER
```
Support using the above mentioned keywords as stream/table attributes. Resolves https://github.com/siddhi-io/siddhi/issues/1742

Add missing Siddhi keywords under 'keyword' section

---

modules/siddhi-core/src/test/java/io/siddhi/core/query/table/cache/CacheCornerCasesTest.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/cache/CacheExpiryAndReloadTestCase.java

> $subject. Fixes the following failures:
```
Identified problems
--
  | testTableJoinQuery1java.lang.ArrayIndexOutOfBoundsException: 1 at io.siddhi.core.query.table.cache.CacheCornerCasesTest.testTableJoinQuery1(CacheCornerCasesTest.java:139)
  | expiryAndReloadTest0java.lang.ArrayIndexOutOfBoundsException: 1 at io.siddhi.core.query.table.cache.CacheExpiryAndReloadTestCase.expiryAndReloadTest0(CacheExpiryAndReloadTestCase.java:70)
  | expiryAndReloadTest1java.lang.ArrayIndexOutOfBoundsException: 1 at io.siddhi.core.query.table.cache.CacheExpiryAndReloadTestCase.expiryAndReloadTest1(CacheExpiryAndReloadTestCase.java:158)
  | expiryAndReloadTest2java.lang.ArrayIndexOutOfBoundsException: 1 at io.siddhi.core.query.table.cache.CacheExpiryAndReloadTestCase.expiryAndReloadTest2(CacheExpiryAndRel …
```

Fix failing test cases in `CacheCornerCasesTest` and `CacheExpiryAndReloadTestCase`

---

modules/siddhi-core/src/main/java/io/siddhi/core/table/Table.java

$title. Fixes https://github.com/siddhi-io/siddhi/issues/1771
```
java.lang.IllegalStateException: MarkIn consecutively called without calling markOut in io.siddhi.SiddhiApps.xxx.Siddhi.Tables.xxx.insert.latency
at io.siddhi.core.util.statistics.metrics.SiddhiLatencyMetric.markIn(SiddhiLatencyMetric.java:55) 
```
> Link(s) to product …

Fix latency tracker markOuts

---

findbugs-exclude.xml
modules/siddhi-core/pom.xml
modules/siddhi-service/pom.xml
pom.xml

> The following changes have been done to address the $subject:
- Update `maven-compiler-plugin`'s `<release>` tag to use Java 11.
- Add javax related dependencies.
- Migrate from findbugs to spotbugs.
- Update `maven-bundle-plugin`'s version to `3.3.0`
Resolves https://github.com/wso2/api-manager/issues/416
> Make Siddhi Compilable on Java11

Compile siddhi on Java11

---

pom.xml

> $subject
> Avoid the following error during build:
```
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  31.376 s
[INFO] [INFO] Finished at: 2022-10-31T21:35:47Z
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:javadoc (docs) on project siddhi-query-api: An error has occurred in Javadoc report generation: 
[INFO] [ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed …
```

Set source to 1.8 in javadoc plugin configurations

---

modules/siddhi-core/src/main/java/io/siddhi/core/query/input/ProcessStreamReceiver.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/SingleProcessStreamReceiver.java

Resolves [issue#1790](https://github.com/siddhi-io/siddhi/issues/1790)
make `SingleProcessStreamReceiver` always synchronize `patternSyncObject` before locking the `lockWrapper` in `process` method
1 Modify `ProcessStreamReceiver#process` to be protected method
2 Overwrite the `process` mothod in `SingleProcessStreamReceiver`,  in the method we synchronize the `patternSyncObject` first then call the `process` method of super class
3 delete synchronization of  `patternSyncObject` in the `processAndClear` method
Fix deadlock on sending data concurrently to pattern query
N/A
N/A
- Confirmed that this PR doesn't commit any keys, …

Fix deadlock on sending data concurrently to pattern query

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiConstants.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SiddhiAppParser.java

When number of triggers per a siddhi application exceeds 6, triggers won't reinitialize after db re-connection due to hard corded core pool size of 5. https://github.com/wso2-support/siddhi/blob/8b1ace31c1d645d5a2fc47844a5a55ef6ddd282d/modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SiddhiAppParser.java#L162.
Thus, this PR makes siddhi application core thread pool size configurable.
Here, if the following config is added to the `conf/worker/deployment.yaml` file, the value given in the config as  \<APP_THREAD_POOL_SIZE> would be used as the core pool size. If not, default value of 5 would be used as the core pool size.
```
siddhi:
properties:
appThreadPoolSize: <APP_THREAD_POOL_SIZE>
```
e.g:
```
siddhi:
properties:
appThreadPoolSize: 10
```
**Issue link:** …

[4.x.x] Make siddhi application core thread pool size configurable

---

findbugs-exclude.xml
modules/siddhi-core/src/main/java/io/siddhi/core/SiddhiAppRuntimeImpl.java
modules/siddhi-core/src/main/java/io/siddhi/core/trigger/CronTrigger.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/TemplateBuilder.java

Related Issue: https://github.com/wso2/api-manager/issues/1991

Improve SPLIT_PATTERN to fix mapping errors with advance json objects

---

pom.xml

Update log4j version to 2.22.1. Many libraries (Spring, etc) have moved onto log4j 2.22.1. This causes conflict and breaks the build when Siddhi library is present. 
The fix is to simply cut a new release of Siddhi with upgraded log4j version. 
Update log4j version to 2.22.1, so Siddhi could work with latest version of many other libraries.

Upgrade log4j version to 2.22.1

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/config/YAMLConfigManager.java
modules/siddhi-core/src/test/java/io/siddhi/core/stream/FaultStreamTestCase.java
modules/siddhi-feature/pom.xml
pom.xml

This PR will update the following 3rd party dependencies.
- guava - 33.0.0
- slf4j - 2.0.11
- gson - 2.10.1
- jackson-datatype-joda - 2.16.0
- commons.io - 2.15.1
- snakeyaml -2.2

Upgrade 3rd party dependencies

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiExtensionLoader.java

$subject
Unable to use try with resources block as the default java version specified is Java 6[1] which does not support try with resources.
[1] https://github.com/siddhi-io/siddhi/blob/3.2.x/pom.xml#L315

Close BufferedReader in SiddhiExtensionLoader

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutorsInitialiser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/IncrementalTimeConverterUtil.java

To handle the possible OOM issue in Analytics nodes when processing non-aggregated data while starting the server.
Fixes: https://github.com/siddhi-io/siddhi/issues/1830
Improved aggregation initialization by limiting the number of columns loaded to the in-memory for Persisted aggregation.
Original PR: https://github.com/wso2-support/siddhi/pull/257

Improve aggregation initialisation

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/processor/executor/GroupByAggregationAttributeExecutor.java

> Memory is growing continuously in Control Plane node each time when redeploying a throttling policy leading to high CPU and memory usage and OOM scenarios.
Related Issue : https://github.com/wso2/api-manager/issues/3815
> Stop memory growth when redeploying a throttling policy.
> Clear the old throttle policy trackers when throttle policy is redeployed.

Clear expired throttle policy trackers when throttle policy is redeployed
