siddhi-io/siddhi

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/stream/populater/ComplexEventPopulater.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/stream/populater/SelectiveComplexEventPopulater.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/stream/populater/StreamEventPopulaterFactory.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/extension/holder/StreamFunctionProcessorExtensionHolder.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/AbstractStreamProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/StreamProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/function/StreamFunctionProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/TableWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/WindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/InputStreamParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/JoinInputStreamParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SingleInputStreamParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StateInputStreamParser.java

- Renamed `StreamEventPopulater` to `ComplexEventPopulater` as it populates any `ComplexEvent`.
- `StreamProcessor` can now process only `StreamEvents`

Change StreamFunctionProcessor to extend from AbstractStreamProcessor

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/LengthBatchWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/TimeBatchWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/QuerySelector.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggergator/AttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/processor/AttributeProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/processor/executor/GroupByAggregationAttributeExecutor.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/ratelimit/SnapshotOutputRateLimitTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/LenghtBatchWindowTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/TimeBatchWindowTestCase.java

Revert "Using reset events for batch processing" until the change is reviewed completely.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggergator/StddevAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/StddevAttributeAggregator.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/StddevAttributeAggregatorTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/stream_function/Pol2CartFunctionTestCase.java

Please find the associated Jira issue below:
https://wso2.org/jira/browse/CEP-107
More details on the algorithm used for computing running varience is in the
article by John D. Cook. Find it in the follwing link.
http://www.johndcook.com/blog/standard_deviation/
I only ~~implemented~~ tested `Stddev` for type `Double` for the time being.

Implement stddev

---

modules/siddhi-core/pom.xml
modules/siddhi-samples/performance-samples/pom.xml
modules/siddhi-samples/pom.xml
modules/siddhi-samples/quick-start-samples/pom.xml
pom.xml

Disruptor updated to latest version 3.3.0

---

modules/siddhi-extensions/event-table/pom.xml
pom.xml

Fix Import-Package version issue for log4j dependency

Fix Import-Package version issue for log4j dependency

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/StreamStatLogger.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PersistenceTestCase.java

Signed-off-by: sajith <sajithshn@gmail.com>

Fixing persistant test case failure

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/sequence/SequenceTestCase.java

Signed-off-by: sajith <sajithshn@gmail.com>

Fixing test failiure

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/ratelimit/SnapshotOutputRateLimitTestCase.java

Signed-off-by: sajith <sajithshn@gmail.com>

Fixing testSnapshotOutputRateLimitQuery14 test case

---

.gitignore
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/ExternalTimeBatchWindowProcessor.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/ExternalTimeBatchWindowTestCase.java

This includes the changes in https://github.com/wso2/siddhi/pull/102  +  formatting and minor changes

CEP-1441: External Batch window (modified)

---

.gitignore
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/ExternalTimeBatchWindowProcessor.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/ExternalTimeBatchWindowTestCase.java

Add external time batch window implementation.

CEP-1441: External Batch window

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/join/JoinTestCase.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/HazelcastEventTable.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/hazelcast/HazelcastEventTableConstants.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/hazelcast/HazelcastIndexedOperator.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/hazelcast/HazelcastOperator.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/hazelcast/HazelcastOperatorParser.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/hazelcast/internal/ds/HazelcastEventTableServiceDS.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/hazelcast/internal/ds/HazelcastEventTableServiceValueHolder.java
modules/siddhi-extensions/event-table/src/main/resources/eventtable.siddhiext
modules/siddhi-extensions/event-table/src/test/java/org/wso2/siddhi/extension/eventtable/hazelcast/DefineTableTestCase.java
modules/siddhi-extensions/event-table/src/test/java/org/wso2/siddhi/extension/eventtable/hazelcast/DeleteFromTableTestCase.java
modules/siddhi-extensions/event-table/src/test/java/org/wso2/siddhi/extension/eventtable/hazelcast/IndexedTableTestCase.java
modules/siddhi-extensions/event-table/src/test/java/org/wso2/siddhi/extension/eventtable/hazelcast/InsertIntoTableTestCase.java
modules/siddhi-extensions/event-table/src/test/java/org/wso2/siddhi/extension/eventtable/hazelcast/JoinTableTestCase.java
modules/siddhi-extensions/event-table/src/test/java/org/wso2/siddhi/extension/eventtable/hazelcast/UpdateFromTableTestCase.java
modules/siddhi-extensions/event-table/src/test/java/org/wso2/siddhi/extension/eventtable/test/util/SiddhiTestHelper.java

Hazelcast Event Table Fixed, Refactored, and Reformatted according to the feedback on #80. Please review and merge.

Fixing Hazelcast Event Table

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/ExecutionPlanRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/config/ExecutionPlanContext.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/callback/QueryCallback.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/StreamJunction.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/SingleStreamEntryValve.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/StreamCallback.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/stream/ExceptionHandlerTestCase.java

Thanks @haoch (Hao Chen) for the contribution.

Fix for https://wso2.org/jira/browse/CEP-1411 

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/ratelimit/SnapshotOutputRateLimitTestCase.java

Fixed SnapshotOutputRateLimit test case. Please review and merge.

Fixed SnapshotOutputRateLimit test case

---

modules/siddhi-extensions/distinct/pom.xml
modules/siddhi-extensions/distinct/src/main/java/org/wso2/siddhi/extension/distinct/CountAggregateFunction.java
modules/siddhi-extensions/distinct/src/main/resources/distinct.siddhiext
modules/siddhi-extensions/distinct/src/test/java/org/wso2/siddhi/extension/distinct/CountAggregateFunctionTestCase.java
modules/siddhi-extensions/distinct/src/test/resources/log4j.properties
modules/siddhi-extensions/pom.xml

Added the implementation of distinct count aggregate extension. Please review and merge.

Distinct Count Aggregator

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/ExternalTimeBatchWindowProcessor.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/ExternalTimeBatchWindowTestCase.java

ExternalTimeBatchWindow Modifications 

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/config/ExecutionPlanContext.java

Fix for [1], `ConcurrentModificationException` on ExecutionPlan validation. Please review and merge.
[1] https://wso2.org/jira/browse/CEP-1491

Fixed CEP-1493

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/TimeBatchWindowProcessor.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/TimeBatchWindowTestCase.java

emitting expired events on round times

adding start time for time batch window

---

modules/siddhi-extensions/math/src/main/java/org/wso2/siddhi/extension/math/PercentileFunctionExtension.java

modifications according to the discussion - [https://github.com/wso2/siddhi/pull/158#discussion-diff-66780639](url)

Adding an instanceof check instead of catching a ClassCastException

---

modules/siddhi-extensions/reorder/src/test/java/org/wso2/siddhi/extension/reorder/KSlackExtensionTestCase.java

Added a fixed time-out value 1000 as the second parameter to the kslack extension call.

Added a fixed time-out value 1000 as the second parameter to the kslack extension call.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/InMemoryEventTable.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/HazelcastEventTable.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/RDBMSEventTable.java

Possible concurrent issues in other operators also fixed through synchronization.

Fixing concurrent issue in SimpleOperator

---

modules/siddhi-extensions/math/pom.xml
modules/siddhi-extensions/math/src/main/java/org/wso2/siddhi/extension/math/PercentileFunctionExtension.java
modules/siddhi-extensions/math/src/test/java/org/wso2/siddhi/extension/math/PercentileFunctionExtensionTestCase.java

Removing apache commons Descriptivestatistics library and implementing percentile calculation function inside the siddhi in order to improve the performance.

Improving performance of the percentile extension 

---

modules/siddhi-extensions/map/pom.xml
modules/siddhi-extensions/map/src/main/java/org/wso2/siddhi/extension/map/CreateFromXMLFunctionExtension.java

Fix for [1], Parsing issue in map:createFromXML(). Please review and merge.
[1] https://wso2.org/jira/browse/CEP-1530

Fixed CEP-1530

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/MultiProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/join/JoinProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/join/JoinStreamRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/JoinInputStreamParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/QueryParserHelper.java

JoinProcessors share the same lock of Query as well as Schedulers

Remove pre JoinProcessor and fix possible concurrent issue in join

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/executor/function/IfThenElseFunctionExecutor.java

Fixed [1] and added short-circuiting, instead of evaluating both "Then" and "Else" expressions prior to "If" condition. Please review and merge.
[1] https://wso2.org/jira/browse/SIDDHI-27

Fixed SIDDHI-27

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/executor/function/ConvertFunctionExecutor.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/ConvertFunctionTestCase.java

Fixed [1], of having possible NPE in convert() function. Please review and merge.
[1] https://wso2.org/jira/browse/SIDDHI-26

Fixed SIDDHI-26

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/debugger/SiddhiDebuggerClient.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/debugger/TestDebugger.java

Add input validation
Fixed a possible bug in TestDebugger test case

Move SiddhiDebuggerClient to src

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/InMemoryOutputTransport.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/OutputMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/OutputTransport.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/EventTable.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/InMemoryEventTable.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/collection/UpdateAttributeMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/collection/operator/Operator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/transport/OptionHolder.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/aggregator/MaxForeverAggregatorExtensionTestCase.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/HazelcastEventTable.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/RDBMSEventTable.java
modules/siddhi-extensions/output-transports/kafka-output-transport/src/main/java/org/wso2/siddhi/extension/output/transport/kafka/KafkaOutputTransport.java
modules/siddhi-extensions/output-transports/tcp-output-transport/src/main/java/org/wso2/siddhi/extension/output/transport/tcp/TcpOutputTransport.java

and also Removing unnecessary arguments to event table init()

Simplifying transport initialization 

---

modules/siddhi-extensions/input-transports/kafka-input-transport/src/main/java/org/wso2/siddhi/extension/input/transport/kafka/ConsumerKafkaGroup.java
modules/siddhi-extensions/input-transports/kafka-input-transport/src/main/java/org/wso2/siddhi/extension/input/transport/kafka/KafkaConsumerThread.java
modules/siddhi-extensions/input-transports/kafka-input-transport/src/main/java/org/wso2/siddhi/extension/input/transport/kafka/KafkaInputTransport.java
modules/siddhi-extensions/input-transports/kafka-input-transport/src/test/java/org/wso2/siddhi/extension/input/transport/kafka/KafkaInputTransportTestCase.java
modules/siddhi-extensions/output-transports/kafka-output-transport/src/main/java/org/wso2/siddhi/extension/output/transport/kafka/KafkaOutputTransport.java
modules/siddhi-extensions/output-transports/kafka-output-transport/src/test/java/org/wso2/siddhi/extension/output/transport/kafka/KafkaOutputTransportTestCase.java

Adding Threading options to kafka consumer (single threaded, topic wise, partition wise)

Adding threading options to kafka receiver,

---

modules/siddhi-extensions/input-transports/tcp-input-transport/src/test/java/org/wso2/siddhi/extension/input/transport/tcp/TCPInputTransportTestCase.java
modules/siddhi-extensions/transport/tcp-transport/src/main/java/org/wso2/siddhi/tcp/transport/TCPNettyServer.java

and testing pause and resume across multiple clients

making the flow control handler sharable 

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/ExecutionPlanRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/Event.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/CountAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/OutputMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/OutputTransport.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/PassThroughOutputMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/AsyncSnapshotPersistor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PersistenceTestCase.java
modules/siddhi-extensions/input-transports/kafka-input-transport/pom.xml
modules/siddhi-extensions/input-transports/kafka-input-transport/src/main/java/org/wso2/siddhi/extension/input/transport/kafka/ConsumerKafkaGroup.java
modules/siddhi-extensions/input-transports/kafka-input-transport/src/main/java/org/wso2/siddhi/extension/input/transport/kafka/KafkaConsumerThread.java
modules/siddhi-extensions/input-transports/kafka-input-transport/src/main/java/org/wso2/siddhi/extension/input/transport/kafka/KafkaInputTransport.java
modules/siddhi-extensions/input-transports/kafka-input-transport/src/test/java/org/wso2/siddhi/extension/input/transport/kafka/KafkaInputTransportTestCase.java
modules/siddhi-extensions/output-mappers/text-output-mapper/src/main/java/org/wso2/siddhi/extension/output/mapper/text/TextOutputMapper.java
pom.xml

The initial version of the single node High availability support for Siddhi with Kafka transport.

HA feature - initial version

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/record/ConditionBuilder.java

Fix issue in handling stream variables within conditions

---

findbugs-exclude.xml
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/SiddhiEventFactory.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/stream/StreamEventFactory.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/stream/StreamEventPool.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/executor/condition/NotConditionExpressionExecutor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/join/JoinProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/snapshot/AggregationGroupByWindowedPerSnapshotOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/snapshot/AggregationWindowedPerSnapshotOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/snapshot/WrappedSnapshotOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/StreamJunction.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/InputEventHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/record/AbstractRecordTable.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/ExecutionPlanRuntimeBuilder.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/stream/event/EventTestCase.java
modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/definition/FunctionDefinition.java

This PR contains fixes made as per suggestions of findbugs. Functionality verified by running tests

Findbug suggested fixes

---

modules/siddhi-annotations/src/main/java/org/wso2/siddhi/annotation/processor/SiddhiAnnotationProcessor.java
modules/siddhi-annotations/src/main/java/org/wso2/siddhi/annotation/util/AnnotationConstants.java

Fix for annotation validation error

Specifying correct superclass for event tables

---

pom.xml

upgrading com.fasterxml.jackson.core version from 2.6.3 to 2.7.4

---

findbugs-exclude.xml
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/debugger/SiddhiDebugger.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/event/FirstGroupByPerEventOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/event/LastGroupByPerEventOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/snapshot/AggregationGroupByWindowedPerSnapshotOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/snapshot/AggregationWindowedPerSnapshotOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/snapshot/AllAggregationGroupByWindowedPerSnapshotOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/snapshot/AllAggregationPerSnapshotOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/snapshot/GroupByPerSnapshotOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/snapshot/PerSnapshotOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/snapshot/WindowedPerSnapshotOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/time/AllPerTimeOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/time/FirstGroupByPerTimeOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/time/FirstPerTimeOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/time/LastGroupByPerTimeOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/time/LastPerTimeOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/ExternalTimeBatchWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/FrequentWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/LengthBatchWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/LengthWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/LossyFrequentWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/SortWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/TimeBatchWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/MaxAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/MinAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/JoinInputStreamParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java

In synchronization fixes currentState() and restoreState() is synchronized which will have no effect on event flow. However in Max/Min aggregator had to synchronize reset(). That change is seperated out is commit named 'synchronize reset method of aggregator make class thread safe'. Please have a look at that.

Find bugs suggested fixes

---

modules/siddhi-annotations/src/main/java/org/wso2/siddhi/annotation/processor/AbstractAnnotationProcessor.java

This will provide users to have numbers only at the end.
eg: abc2.def.igk456

Changing PARAMETER_NAME_PATTERN to have numbers only at the end

---

docs/documentation.md
modules/siddhi-core/siddhi-core-doc-gen/pom.xml
modules/siddhi-doc-gen/pom.xml
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/commons/ExampleMetaData.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/commons/ExtensionMetaData.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/commons/ExtensionType.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/commons/NamespaceMetaData.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/commons/ParameterMetaData.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/commons/ReturnAttributeMetaData.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/commons/SystemParameterMetaData.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/DocumentationGenerationMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/freemarker/FormatDescriptionMethod.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/Constants.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/DocumentationUtils.java
modules/siddhi-doc-gen/src/main/resources/templates/documentation.md.ftl
pom.xml

This PR contains
- Siddhi doc generation plugin module
- Siddhi core doc generation module created for generating documentation for siddhi core (As a solution to the circular dependency which would otherwise exist)
- Generated documentation file for siddhi core; docs/documentation.md

Add Siddhi Doc Generation Plugin Module

---

modules/siddhi-annotations/src/main/java/org/wso2/siddhi/annotation/processor/FunctionExecutorValidationAnnotationProcessor.java
modules/siddhi-doc-gen/src/main/resources/templates/documentation.md.ftl

Function executor processor dynamic parameter validation message improve.
Doc generator parameter table "Parameter Type" refactoring to "Parameter Data Type".

Validation Annotation Processor Improvement.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/table/DefineTableTestCase.java

1. Support to override properties defined under store in configurations
2. Check for pointing to undefined store
3. Improved test cases

Improved store ref support

---

coverage-reports/pom.xml
modules/siddhi-core/pom.xml
modules/siddhi-query-api/pom.xml
modules/siddhi-query-compiler/pom.xml
pom.xml

Additionally aggregated all individual  reports

Jacoco code coverage report generation enabled to siddhi-core, siddhi-query-compiler and siddhi-query-api

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiManager.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/persistence/PersistenceService.java

Implemented method in SiddhiManager to return list of SiddhiAppRuntimes.
Restoring last revision of SiddhiApp will return the revision name being restored.

SiddhiManager returns SiddhiAppRuntimes. Restoring siddhiapp state return revision name.

---

modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/ExtensionsIndexGenerationMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/MarkdownDocumentationGenerationMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/MkdocsGitHubPagesDeployMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/Constants.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/DocumentationUtils.java
modules/siddhi-doc-gen/src/main/resources/templates/headings-update.md.ftl

This PR contains the support to change the content of predefined headings in the README.md file. The functionality is similar to that used for updating the index file of the documentation.

Bug Fix to Siddhi Doc Gen Plugin - Add support to update the README.md using predefined headings

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/executor/condition/AndConditionExpressionExecutor.java

Optimize AND ExpressionExecutor to return false asap.

---

modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/MkdocsGitHubPagesDeployMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/Constants.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/DocumentationUtils.java
modules/siddhi-doc-gen/src/main/resources/templates/headings-update.md.ftl

Revert "Siddhi Doc Gen Plugin - change the mkdocs gh-deploy to a manual git push"

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/TestUtil.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/absent/AbsentPatternTestCase.java

Hi,
As we have discussed during the last code review, I have created a new class `TestUtil` to store the runtime assertions and throw them later. Could you please check the design, class name and the package location.
**Note: This PR contains only the prototype. Please do not merge it.**
Thanks

[FYI Only] TestUtil to create callbacks in unit tests

---

docs/extensions.md
modules/siddhi-core/siddhi-core-doc-gen/pom.xml

Add siddhi-execution-kalmanfilter and siddhi-map-keyvale extension to the siddhi documentation.

edit siddhi-core-doc-gen/pom.xml

---

README.md
docs/api/4.0.0-M78-SNAPSHOT.md
docs/extensions.md
docs/index.md
mkdocs.yml
modules/siddhi-core/siddhi-core-doc-gen/pom.xml

Add siddhi-gpl-execution-streamingml extension to the siddhi site.

Add siddhi-gpl-execution-streamingml extension to the siddhi site.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/partition/PartitionRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/partition/PartitionStreamReceiver.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/partition/PartitionTestCase.java

- Throw a ExecutionPlanCreationException from PartitionRuntime if there's such a case occured from API level.
- Adding test case for the scenario where no executor has been provided…

Improving code coverage of org.wso2.siddhi.core.query.partition

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/TableWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/TimeWindowProcessor.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PersistenceTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/FirstUniqueWindowTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/SortWindowTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/TimeWindowTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/UniqueWindowTestCase.java
modules/siddhi-extensions/event-table/src/test/java/org/wso2/siddhi/extension/eventtable/rdbms/DeleteFromRDBMSTestCase.java
modules/siddhi-extensions/event-table/src/test/java/org/wso2/siddhi/extension/eventtable/rdbms/InsertIntoRDBMSTestCase.java
modules/siddhi-extensions/event-table/src/test/java/org/wso2/siddhi/extension/eventtable/rdbms/UpdateFromRDBMSTestCase.java

Improve the test coverage 

---

README.md
docs/index.md
mkdocs.yml
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/BooleanCompareTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/StringCompareTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

Added testcases for Siddhi.core.query

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/config/ConfigManager.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/config/InMemoryConfigManager.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/table/DefineTableTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/table/util/TestStore.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/transport/InMemoryTransportTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/transport/MultiClientDistributedSinkTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/transport/SingleClientDistributedTransportTestCases.java
modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/definition/TableDefinition.java

Supporting  Source, Sink, and Destination annotation to use system defined 'ref' parameter to pick values from the system.

Extending ref support for Source, Sink and Destination

---

mkdocs.yml
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/Constants.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/DocumentationUtils.java

Trying to fix github page loading issue
Github pages are not updated on release, this try to fix that

Fix github page loading issue

---

modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/Constants.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/DocumentationUtils.java

Changing the git push url to ssh
Github pages are not updated on release, this try to fix that

Changing the Git push url to ssh

---

modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/Constants.java

Reverting the url to ssh

---

modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/rdbms/DBHandler.java

Resolves #572 & #592 in 3.1.x
> #574

Fix for #572 & #592 in 3.1.x

---

docs/documentation/siddhi-4.0.md

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Siddhi Guide review - Tables.

---

docs/documentation/siddhi-4.0.md

Updated the Windows section of the Siddhi Guide.

Siddhi Guide Review - Windows.

---

docs/api/latest.md
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/partition/PartitionTestCase.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/DocumentationUtils.java

Fixing test and build issue

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/CastFunctionExecutorTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/ConvertFunctionTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/InstanceOfFunctionTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/MaximumFunctionExtensionTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/MinimumFunctionExtensionTestCase.java

Porting siddhi core test case from siddhi 3.1x branch
to increase the test coverage
Written test cases for missed out execution lines

ported siddhi core test case from siddhi 3.1x branch

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceMapper.java

> Implementing getter method for Source Handler

Adding getter for Source Handler

---

docs/documentation/siddhi-architecture.md

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Reviewing the Siddhi Architecture page.

---

docs/documentation/siddhi-4.0.md
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/metrics/SiddhiStatisticsManager.java

>Improve Siddhi doc, by adding SiddhiApp format
> Help user know siddhi app looks like

Adding SiddhiApp format to the docs

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/MultiProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/ProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/SingleProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/StateMultiProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/receiver/PatternMultiProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/receiver/PatternSingleProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/receiver/SequenceMultiProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/receiver/SequenceSingleProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/OutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/Scheduler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiAppRuntimeBuilder.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/InputStreamParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/JoinInputStreamParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StateInputStreamParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/partition/JoinPartitionTestCase.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/DocumentationUtils.java

fixing doc gen and fixing build

---

README.md

> Reviewed README.md for Siddhi.

Reviewed README.md for Siddhi.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/LogSink.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/UnitTestAppender.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/stream/output/sink/LogSinkTest.java
modules/siddhi-core/src/test/resources/testng.xml

To add logger sink. 
Avoid having to write another query when we have to log the events from output stream
implementing a sink that imitates the work of log SP

adding logger sink

---

README.md

> Easy access to web sites
>Increase the personal reach of the company and the university

Added links to University of Moratowa and WSO2 websites in the read

---

docs/api/latest.md
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiAppRuntimeBuilder.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SiddhiAppParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/StatisticsManager.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/StatisticsTrackerFactory.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/metrics/SiddhiMetricsFactory.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/commons/metadata/ExtensionMetaData.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/commons/metadata/NamespaceMetaData.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/utils/DocumentationUtils.java

>Improving statistics APIs to support better stats generation, Fixing the order of API doc content. Fixing line number reporting to definitions.
> Improving usability

Improving statistics APIs to support better stats generation, Fixing the  order of API doc content. Fixing line number reporting to definitions.

---

docs/documentation/siddhi-quckstart-4.0.md

> Corrected a minor error in the Quick Start Guide.

Corrected a minor error in the Quick Start Guide.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiExtensionLoader.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiManagerComponent.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/AggregationParser.java

> Fix for OSGi based extension loading issue.

Fix for OSGi based extension loading issue

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/stream/StreamEventFactory.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/stream/StreamEventPool.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/stream/converter/StreamEventConverter.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PersistenceTestCase.java

> Fix for https://wso2.org/jira/browse/DAS-544

Fix for https://wso2.org/jira/browse/DAS-544

---

modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/rdbms/DBHandler.java

> Adding logs to the DBHandler (https://wso2.org/jira/browse/DAS-547)

Adding logs to the DBHandler (https://wso2.org/jira/browse/DAS-547)

---

modules/siddhi-service/pom.xml
modules/siddhi-service/src/main/java/org/wso2/siddhi/service/impl/SiddhiApiServiceImpl.java
modules/siddhi-service/src/test/java/org/wso2/siddhi/service/SiddhiApiTestCase.java
modules/siddhi-service/src/test/resources/testng.xml

>Resolves https://github.com/wso2/siddhi/issues/641
> Use Siddhi App name as key for map
- Unit tests 
org.wso2.siddhi.service.SiddhiApiTestCase#testDeployAndUndeploy
> Details about the test cases and coverage
JDK 1.8.0

fixing #641 and adding tests

---

docs/documentation/siddhi-4.0.md

Fix typo in table definition syntax

fix table definition syntax

---

modules/siddhi-extensions/event-table/pom.xml
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/rdbms/DBQueryHelper.java

> Improve xml parsing logic
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Improve xml parsing logic

---

docs/documentation/siddhi-4.0.md

from 
different type of functionality, and for come cases there can be gaps and you need to write the functionality by yourself.
to
different type of functionality, and for some cases there can be gaps and you need to write the functionality by yourself.
to Fix the spelling mistake at line number 2045

fixed the spelling mistake at line number 2045

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/StreamJunction.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/window/Window.java

> Remove  unnecessary metrics calculations to improve performance
> When metrics are off it should not be used for calculation

Skipping unnecessary metrics calculations

---

docs/documentation/siddhi-4.0.md

from 
in the syntax. For more information, see [output event type](http://127.0.0.1:8000/documentation/siddhi-4.0/#output-event-types).
to
in the syntax. For more information, see [output event type](#output-event-types).
To fix a broken link

Fixed a broken link in line number 1589

---

modules/siddhi-query-compiler/src/main/antlr4/org/wso2/siddhi/query/compiler/SiddhiQL.g4

Simplifying the structure of the join_stream rule
Make a hassle free grammar file
N/A
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests 
N/A
N/A
N/A
N/A
N/A
N/A
N/A.

Simplifying the structure of the join_stream rule

---

docs/documentation/siddhi-4.0.md

Fixes for issues #654, #655, #657
Provide fixes for issues.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests 
N/A
N/A
N/A
N/A
N/A
N/A
N/A

Fixes for issues #654, #655, #657

---

checkstyle-suppressions.xml

This PR contains a fix for the issue #624 
Fixing Issues.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests 
N/A
N/A
N/A
N/A
N/A
N/A
N/A

Fixes #624

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java

Correct checkstyle errors in AggregationRuntime class

Correct checkstyle errors

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/transport/MultiClientDistributedSink.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/transport/MultiClientDistributedSinkTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/transport/TestFailingInMemorySink.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/transport/TestFailingInMemorySink2.java

Fixing checkstyle issues

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/AvgAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/MaxAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/MaxForeverAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/MinAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/MinForeverAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/StdDevAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/SumAttributeAggregator.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/LengthWindowTestCase.java

Fixing null pointer in aggregations 

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/QueryParserHelper.java

> fixing naming issue in metrics

fixing naming for metrics

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/CollectionExpressionParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StoreQueryParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/store/StoreQueryTableTestCase.java

Fixing StoreQuery data retrieval without table name reference

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/QueryParserHelper.java

> Fix naming order for improved reporting

Improving naming in statistics names

---

docs/documentation/siddhi-4.0.md

Renaming 'update or insert' to 'update or insert into'

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java

Adding definition map getters for window and aggregation

Adding definition map getters for window and aggregation

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiAppRuntimeBuilder.java

Adding window and aggregation definition maps to constructor

Adding window and aggregation definition maps to constructor

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/callback/InsertIntoWindowCallback.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/QueryableProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/incremental/Executor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/distributed/DistributedTransport.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/Table.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/record/AbstractQueryableRecordTable.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/record/AbstractRecordTable.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/record/RecordTableHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/InputStreamParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SelectorParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SiddhiAppParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SingleInputStreamParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/BufferedEventsTracker.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/metrics/SiddhiBufferedEventsMetric.java

Fix java doc issues

---

modules/siddhi-core/pom.xml
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/Source.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/Sink.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/Table.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/record/RecordTableHandlerCallback.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/LogEncoder.java
pom.xml

> Encode string before logging
> Add dependency for OWASP
> Encode strings that are being logged which may contain user inputs

Added owasp for encoding strings before logging

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/StreamJunction.java

> Format register bufferedEventsMetrics condition.

Format register bufferedEventsMetrics condition.

---

modules/siddhi-core/pom.xml
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/Source.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/Sink.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/Table.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/LogEncoder.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/StringUtil.java
pom.xml

> Owasp is only needed for logging in html. Hence removed dependency usage and removed CRLF characters only

Removed owasp dependency. Remove CRLF characters only

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiAppRuntimeBuilder.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/InputStreamParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/SimpleQueryValidatorTestCase.java

This PR closes #698  
Enhance user experience
- Unit tests 
org/wso2/siddhi/core/query/SimpleQueryValidatorTestCase#testQueryWithTable
org/wso2/siddhi/core/query/SimpleQueryValidatorTestCase#testQueryWithAggregation
org/wso2/siddhi/core/query/SimpleQueryValidatorTestCase#testQueryWithEveryTable
org/wso2/siddhi/core/query/SimpleQueryValidatorTestCase#testQueryWithEveryAggregation

Fixes #698 

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/StringUtil.java

> Check of string is null before replacing CRLF characters

Null check for CRLF removed strings

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/table/LogicalTableTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

> Fixing a typo in a test class

Fixing a typo

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StoreQueryParser.java

Fix retrieval from Incremental Aggregate logic by removing certain object references from aggregation run-time. Instead they are maintained in the IncrementalAggregateCompileCondition

Fix retrieval from Incremental Aggregate logic

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/AggregationTestCase.java

Fix Checkstyle issues

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiManager.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SnapshotableElementsHolder.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/config/ExecutionPlanContext.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/partition/PartitionRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/join/JoinProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/LengthWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/QuerySelector.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/processor/executor/GroupByAggregationAttributeExecutor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiConstants.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/ExecutionPlanParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/persistence/PersistenceService.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotableElement.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/join/JoinTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/window/CronWindowTestCase.java
modules/siddhi-extensions/event-table/src/main/java/org/wso2/siddhi/extension/eventtable/rdbms/DBHandler.java
modules/siddhi-extensions/event-table/src/main/resources/rdbms-table-config.xml
modules/siddhi-extensions/time/src/test/java/org/wso2/siddhi/extension/time/ExtractAttributesFunctionExtensionTestCase.java

This PR will fix several issues in siddhi 3.1.x branch. 
> Fix known issues before the new siddhi 3.1.x release
> Added already resolved fixes to the 3.1.x branch.
NA
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
NA
Fix with @Anoukh

Resolve known issues in Siddhi 3.1.x

---

docs/documentation/siddhi-4.0.md

Adding archetypes documentation for siddhi docs.
Resolves #745 
Adding archetypes documentation for siddhi docs.
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA

Add archetype documentation for siddhi docs

---

coverage-reports/pom.xml
modules/siddhi-core/pom.xml
modules/siddhi-extensions/eval-script/pom.xml
modules/siddhi-extensions/event-table/pom.xml
modules/siddhi-extensions/geo/pom.xml
modules/siddhi-extensions/kalman-filter/pom.xml
modules/siddhi-extensions/map/pom.xml
modules/siddhi-extensions/markov-models/pom.xml
modules/siddhi-extensions/math/pom.xml
modules/siddhi-extensions/pom.xml
modules/siddhi-extensions/regex/pom.xml
modules/siddhi-extensions/reorder/pom.xml
modules/siddhi-extensions/string/pom.xml
modules/siddhi-extensions/time/pom.xml
modules/siddhi-extensions/timeseries/pom.xml
modules/siddhi-query-api/pom.xml
modules/siddhi-query-compiler/pom.xml
modules/siddhi-samples/performance-samples/pom.xml
modules/siddhi-samples/pom.xml
modules/siddhi-samples/quick-start-samples/pom.xml
pom.xml

Change siddhi version for 3.2.0 release 
Change siddhi version for 3.2.0 release 
Change siddhi version for 3.2.0 release 
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
NA

Change siddhi version for 3.2.0 release

---

docs/documentation/siddhi-4.0.md

Making writing siddhi extensions as a heading

---

README.md

Adding Siddhi idea plugin

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/FindStoreQueryRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/SelectStoreQueryRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/StoreQueryRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/QueryableProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/record/AbstractQueryableRecordTable.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StoreQueryParser.java

Improving the pr #755

---

docs/documentation/siddhi-4.0.md

in the release notes
> Added the "Configuring and Monitoring Siddhi Applications" section to the Siddhi Query Guide.

Added the "Configuring and Monitoring Siddhi Applications" section.

---

docs/documentation/siddhi-4.0.md

Improve documentation: Remove archetypeVersion in the commands given under writing custom extension

---

docs/documentation/siddhi-quckstart-4.0.md

Fix editor port value

---

docs/documentation/siddhi-4.0.md

Did some formatting changes to the "Writing a Custom Extension" subsection of the Siddhi Query Guide.

Did some formatting changes to the "Writing Custom Extensions" section.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/processor/executor/GroupByAggregationAttributeExecutor.java

We identify the memory leak in GroupByAggregationAttributeExecutor, where the aggregate attribute executors added in [1] not completely removed by the fixes given in #739.
With this fixes, we have removed the aggregate objects references from execution plan eternal reference holder by a scheduler.
[1] - https://github.com/wso2/siddhi/blob/3.1.x/modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/AttributeAggregator.java#L41
> Remove all the expired aggregate attribute object references. 
> Remove the expired aggregate attribute object references from eternal reference holder with a scheduler. 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- This is to fix a memory leak. Can be only triggered by log running test.
- Performed the several long-running tests.
- …

Fixes for the OOM issue: wso2/siddhi#778

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/SiddhiExtensionLoader.java

> Fix the issue with extensions loading flow if there are non-existing jars in the classpath: https://github.com/wso2/siddhi/issues/782
> Avoid the file content lookup for non-existing files.
> Verify the file existence and is file check before processing the file path.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> Covered by the existing test as this is in siddhi extension loading flow.
> Same as the unit testing, covered by the existing test as this is in siddhi extension loading flow.
> N/A
> N/A …

Fixes for the Extension Loading issue: wso2/siddhi#782

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/AbstractStreamProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PersistenceTestCase.java

Resolves issue774
List AbstractStreamProcessor into Snapshot Service within clone method
- Unit tests 
> Available
> JDK 1.8.0

fixing partition persistance for stream processors

---

docs/documentation/siddhi-4.0.md

Add order by and limit documentation

---

docs/documentation/siddhi-4.0.md

Improve 'writing custom extension' docs by adding that Extension annotation is needed. Resolves #759
able

Improve writing custom extension docs

---

docs/documentation/siddhi-4.0.md

Fix language issues in added documentation

 Fix language issues in added documentation

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/QueryParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/table/InsertIntoTableTestCase.java

> Fix a bug #801, When use "Group by" with "window.timeBatch", data can't insert into a table.
> The GroupComplexEvent should be converted to Stream Event in OutputCallback class (parent callback implementation).
> As the code shows in QueryParser line: 197 we need to add a group by list check.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for …

Fix a bug #801

---

docs/documentation/siddhi-4.0.md

This PR added improvements in siddhi documentation. This fixes #729, #730 and #731.
https://wso2.github.io/siddhi/documentation/siddhi-4.0/#function
https://wso2.github.io/siddhi/documentation/siddhi-4.0/#window
https://wso2.github.io/siddhi/documentation/siddhi-4.0/#defined-window
https://wso2.github.io/siddhi/documentation/siddhi-4.0/#source
https://wso2.github.io/siddhi/documentation/siddhi-4.0/#sink

Documentation Improvements

---

modules/siddhi-core/siddhi-core-doc-gen/pom.xml

> $subject
> Adding following extensions to the list
- io sqs
- io twitter
- execution env
- execution tensorflow
- store cassandra
- store redis

Add missing extensions to the extension list

---

docs/documentation/siddhi-4.0.md

Fix defined window doc.

---

docs/documentation/siddhi-4.0.md
docs/stylesheets/extra.css

Fix log style and add link to mappers

---

docs/documentation/siddhi-4.0.md

> This will fix a documentation issue which reported in #773

Fix the issue which reported in #773

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/StreamPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java

Fix restore bug and improve log message 

---

docs/documentation/siddhi-4.0.md

Improve siddhi docs

---

docs/documentation/siddhi-4.0.md

Improve siddhi doc

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/LogStreamProcessor.java

Improve siddhi docs for log

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/LogStreamProcessor.java

$subject to adhere to annotation validation

LogStreamStreamProcessor annotation updated by removing dynamic option

---

docs/documentation/siddhi-architecture.md

Fix a typo in siddhi-architecture.md

Fix a typo in siddhi-architecture.md

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/persistence/IncrementalFileSystemPersistenceStore.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/persistence/util/IncrementalSnapshotInfo.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/persistence/util/PersistenceHelper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/IncrementalSnapshot.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/IncrementalPersistenceTestCase.java

> $Subject 
This might affect the DB implementation.

Make Incremental-base and Periodic snapshot as two files.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/Source.java

Improving an error message

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/OutputParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StoreQueryParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/AggregationTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/window/TimeBatchWindowTestCase.java

Introduce a pass-through rate limiter for find store query selector

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/partition/PartitionRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/partition/PartitionStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/PartitionParser.java

Fix partitions test case due to regression

---

modules/siddhi-annotations/src/main/java/org/wso2/siddhi/annotation/processor/AbstractAnnotationProcessor.java

Fixing grouping error in camel case regex

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/transport/DynamicOptions.java

Make getEvent() method in DynamicOptions public

---

modules/siddhi-query-compiler/src/main/antlr4/org/wso2/siddhi/query/compiler/SiddhiQL.g4

Purpose of this PR is to make `app` a keyword in SiddhiQL
This will fix https://github.com/wso2/siddhi/issues/848

Make app a keyword

---

docs/documentation/siddhi-4.0.md
docs/features.md

Improving docs

---

docs/documentation/siddhi-4.0.md

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

find a possible spelling mistake

---

docs/documentation/siddhi-4.0.md

$subject
N/A
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? ye

Fixing http source example in the docs

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/state/StateEvent.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/partition/PartitionRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentLogicalPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentStreamPostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/AbsentStreamPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/CountPostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/LogicalPostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/LogicalPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/PostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/StreamPostStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/StreamPreStateProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/runtime/EveryInnerStateRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/Processor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StateInputStreamParser.java

- `PostStateProcessor#setNextEveryStatePerProcessor` -> `PostStateProcessor#setNextEveryStatePreProcessor`
- `StreamPostStateProcessor#nextStatePerProcessor` -> `StreamPostStateProcessor#nextStatePreProcessor`
- `StreamPostStateProcessor#nextEveryStatePerProcessor` -> `StreamPostStateProcessor#nextEveryStatePreProcessor`

A few refactorings to improve code readability.

---

mkdocs.yml

Fix webpage

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/BatchWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/ChunkWindowProcessor.java

Partially implements requirements stated in #853 
- Supports accumulating the whole incoming events set to a single batch.
- Doesn't support max batch size.
- Unit tests 
- passes all
- passes all
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? **yes**
- Ran FindSecurityBugs plugin and verified report? **yes**
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? **yes**

Preliminary implementation of batch window

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/InMemorySource.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/PassThroughSourceMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/InMemorySink.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/PassThroughSinkMapper.java

> In the existing Doc, sample for `InMemorySink` were wrong. There were additional commas and some missing braces. This is to correct them.
> N/A
> N/A
> N/A
> N/A
> N/A - Just editing samples to fix errors.
> N/A
> N/A - Just editing samples to fix errors.
> N/A
- N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? N/A
- Ran FindSecurityBugs plugin and verified report? N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Fixing issues in Samples

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/exception/SiddhiAppCreationException.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/window/WindowDefinitionTestCase.java

Add type validation for source, sink and store

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/executor/function/CreateSetFunctionExecutor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/UnionSetAttributeAggregator.java

Fix the build failure
Fix the build failure
NA
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
NA

Fix the build failure

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/AndAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/OrAttributeAggregator.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/aggregator/AndAggregatorExtensionTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/aggregator/OrAggregatorExtensionTestCase.java

Adding following two siddhi extensions:
**AND Attribute Aggregator**: 
Returns the results of logical AND operation for all the events, returns true only if all of its operands are true, else false.
```
ex:
Event chunk with [true,false,true,false,false] resulting the false
Event chunk with [true,true,true,true,true] resulting the true
```
**OR  Attribute Aggregator**: 
Returns the results of logical OR operation for all the events, returns false only if all of its operands are false, else true.
```
ex:
Event chunk with [true,false,true,false,false] resulting the true
Event chunk with [false,false,false,false,false] resulting the false
```
> These two siddhi extensions are given the feature to aggregate attributes with AND| OR operation based on the given attribute boolean values. 
> …

Add logical AND operation and logical OR operation Siddhi extensions

---

docs/documentation/user-guide.md

Old repo seems to be missing some JARs and it's not working when using Gradle.
Use another repo.
Change repo URL in the docs.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A

Should't we use this repo?

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PlaybackTestCase.java

Fix test failure

---

docs/documentation/siddhi-4.0.md
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/QuerySelector.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/record/AbstractQueryableRecordTable.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SelectorParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/OrderByLimitTestCase.java
modules/siddhi-query-api/src/main/java/org/wso2/siddhi/query/api/execution/query/selection/Selector.java
modules/siddhi-query-api/src/test/java/org/wso2/siddhi/query/api/SimpleQueryTestCase.java
modules/siddhi-query-compiler/src/main/antlr4/org/wso2/siddhi/query/compiler/SiddhiQL.g4
modules/siddhi-query-compiler/src/main/java/org/wso2/siddhi/query/compiler/internal/SiddhiQLBaseVisitorImpl.java
modules/siddhi-query-compiler/src/test/java/org/wso2/siddhi/query/test/SimpleQueryTestCase.java

 Add offset support for Siddhi to support pagination

---

docs/documentation/siddhi-4.0.md

This completes the documentation review for the Automatic Data Purging for Incremental Analysis feature
Documentation review for the  Automatic Data Purging for Incremental Analysis feature.
Reviewed information added relating to Automatic Data Purging in the "Incremental Aggregation" section of the Siddhi Query Guide [1].
[1] https://wso2.github.io/siddhi/documentation/siddhi-4.0/#incremental-aggregation

This completes the documentation review for the Automatic Data Purging for Incremental Analysis feature

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/Scheduler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SiddhiAppParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/timestamp/TimestampGenerator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/timestamp/TimestampGeneratorImpl.java

Kept the interface to keep the API from breaking

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java

Fix typo and fix case where if error is thrown in startWithoutSources method

Fix typo and error handling

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/AggregationTestCase.java

$subject, Fixes https://github.com/wso2/siddhi/issues/846
N/A

Fix NPE when aggregation read def does not contain per and within

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java

Fix cache growing issue by adding least recently used cache.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java

Purpose of this PR is to $subject.

Fix illegalState exception when removing iterator

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/BatchWindowProcessor.java

> Fixes [#919](https://github.com/wso2/siddhi/issues/919)
> Fix NPE getting thrown when an empty response from the Siddhi RDBMS query extension is batched.
> Check whether the event chunk has next event while batching

Check whether eventChunk hasNext event while batching

---

docs/documentation/siddhi-4.0.md

Update doc on having same aggregation definition in multiple siddhi apps

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/transport/InMemoryTransportTestCase.java

Adjusted InmemoryFailingSource test case waiting time to prevent intermittent test failure

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/AggregationFindQueryValidationTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

$subject. Fixes https://github.com/wso2/siddhi/issues/943
N/A

 Normalisation of time units used in per expression of incremental aggregation find query.

---

docs/documentation/siddhi-4.0.md

To add the information in [1] to Siddhi documentation.
[1] https://www.javahelps.com/2017/08/detect-absence-of-events-wso2-siddhi.html
Added the "Detecting non-occurring events" to the Siddhi query Guide. Please review.

This adds information about non-occurring events to the Siddhi Query Guide.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/state/LogicalPreStateProcessor.java

Fix for the javadoc generation failure

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/DelayWindowProcessor.java

> The documentation in the DelayWindowProcessor.java file was reviewed.

This completes the documentation review for the Delay window.

---

docs/documentation/siddhi-4.0.md
docs/extensions.md

> Adding link to siddhi io cdc

Add siddhi io cdc link

---

modules/siddhi-service/pom.xml
modules/siddhi-service/src/main/bin.xml
modules/siddhi-service/src/main/resources/startup.sh

Fix Siddhi microservices

---

docs/extensions.md

 Add all extensions to site

---

docs/documentation/siddhi-4.0.md

Connect log sink documentation

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/RecreateInMemoryData.java

$subject
Filtering with having clause is translators to erroneous SQL query
Changed as on condition which translates to where clause
N/A

[Partial Aggregation] Change shard Id filtering to on condition

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/config/ConfigManager.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/config/InMemoryConfigManager.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/AggregationParser.java

This is to introduce a new APi for siddhi config manager to extract 'properties' from siddhi configurations.

Introduce 'properties' for siddhi configurations

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/config/InMemoryConfigManager.java

Refactor code

---

modules/siddhi-core/siddhi-core-doc-gen/pom.xml

Link siddhi-io-cdc from extensions.md page

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/LengthBatchWindowProcessor.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/window/LenghtBatchWindowTestCase.java

Fix bug of lengthBatch(1) window to separate events by one

---

docs/documentation/siddhi-4.0.md

Fix formatting in doc distributed aggregation

---

docs/api/latest.md
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/MultiProcessStreamReceiver.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/pattern/EveryPatternTestCase.java

> Fix $Subject
> Issue introduced in Siddhi 4.3.0.

Fix bug Siddhi pattern trigger only once #981 when every is used.

---

docs/documentation/siddhi-4.0.md

> Add avro mapper to siddhi documentation

Add avro mapper to siddhi documentation

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/LogSink.java

Fix syntax error in logsink example

---

docs/documentation/siddhi-4.0.md

> Use self-explanatory example in the Fault Stream documentation

Refactor Fault Stream documentation

---

modules/siddhi-core/pom.xml
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PlaybackTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/StatisticsTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/trigger/TriggerTestCase.java
modules/siddhi-core/src/test/resources/testng.xml
modules/siddhi-query-api/pom.xml
modules/siddhi-query-api/src/test/resources/testng.xml
modules/siddhi-query-compiler/pom.xml
modules/siddhi-query-compiler/src/test/resources/testng.xml

Make test run parallel

---

modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/ExtensionsIndexGenerationMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/MarkdownDocumentationGenerationMojo.java
modules/siddhi-doc-gen/src/main/java/org/wso2/siddhi/doc/gen/core/MkdocsGitHubPagesDeployMojo.java
pom.xml

Remove WSO2 parent pom reference with required fixes

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/IncrementalPurgingTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PlaybackTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/ratelimit/TimeOutputRateLimitTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

Fix intermittent test failure

---

docs/documentation/siddhi-4.0.md

Docs for non standard IDs using ``

---

docs/documentation/siddhi-4.0.md
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/streamfunction/AttributeStreamFunction.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/streamfunction/StreamFunctionTestCase.java
modules/siddhi-core/src/test/resources/testng.xml
modules/siddhi-query-compiler/src/main/antlr4/org/wso2/siddhi/query/compiler/SiddhiQL.g4

This allows us to define and use streams as
```
define stream `$InputStream` (`56$2theta` double, rho double);
```

 Support non standard IDs using ``

---

modules/siddhi-core/pom.xml
modules/siddhi-query-api/pom.xml
modules/siddhi-query-compiler/pom.xml
modules/siddhi-samples/performance-samples/pom.xml
modules/siddhi-samples/pom.xml
modules/siddhi-samples/quick-start-samples/pom.xml
modules/siddhi-service/pom.xml
pom.xml

> Use vanilla versions of the jars when possible. Fix issue https://github.com/siddhi-io/siddhi/issues/768

Remove WSO2 modified dependencies 

---

pom.xml

$subject after repo moved from wso2 to siddhi-io org
N/A

Change scm

---

docs/documentation/siddhi-4.0.md

$subject to Incremental Aggregation docs
N/A as this is a doc fix

Add AGG_TIMESTAMP to docs

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/Aggregation1TestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/Aggregation2TestCase.java

1. Reorder the asserts for easier debugging
2. Include AGG_TIMESTAMP in asserts for accuracy
Partially solves https://github.com/siddhi-io/siddhi/issues/990
N/A

Refactor Aggregation testcases

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceMapper.java

> Add stack trace to the error log

Add stack trace to the error log

---

docs/documentation/siddhi-4.0.md

Fix issue https://github.com/siddhi-io/siddhi/issues/732

Add @store to the docs

---

docs/documentation/siddhi-4.0.md

Fix issue https://github.com/siddhi-io/siddhi/issues/997

Describe join operations for tables, windows and aggregations

---

README.md

Update Siddhi features

---

README.md
docs/features.md
issue_template.md

Add features and improve issue template

Add features and improve issue template

---

README.md
docs/index.md

Fix mkdocs

---

README.md
docs/index.md

Fix mkdocs style issue

---

modules/siddhi-core/src/main/java/io/siddhi/core/query/processor/stream/window/BatchWindowProcessor.java
modules/siddhi-core/src/test/java/io/siddhi/core/window/BatchWindowTestCase.java

> Resolve the issue #853
> Chunk the batch stream into multiple chunks and add a reset event at the end of each chunk.

Add chunking capability to the batch window

---

docs/api/latest.md
modules/siddhi-core/src/test/java/io/siddhi/core/window/LengthBatchWindowTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/window/LengthWindowTestCase.java
modules/siddhi-core/src/test/resources/testng.xml
modules/siddhi-query-compiler/src/test/java/io/siddhi/query/test/SimpleQueryTestCase.java
modules/siddhi-query-compiler/src/test/resources/test.txt

Fix length window typo

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiTestHelper.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation1TestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/IncrementalPurgingTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/MultiClientDistributedSinkTestCase.java

In Siddhi, following test fail intermittently. 
```
- Aggregation1TestCase.incrementalStreamProcessorTest6: In events matched expected:<true> but was:<false>
- Aggregation1TestCase.incrementalStreamProcessorTest7: In events matched expected:<true> but was:<false>
- Aggregation1TestCase.incrementalStreamProcessorTest46: In events matched expected:<true> but was:<false>
- MultiClientDistributedSinkTestCase.multiClientFailingBroadcast3: Number of topic 1 events expected:<6> but was:<5>
- IncrementalPurgingTestCase.incrementalPurgingTest2
```
Therefore in order to stabilize the build, the above tests need to be fixed or add more information to rectify those failures. This PR fixes some of the failures while improving others to rectify the issue later.
Following fixes has been carried out for …

Fix intermittent test failures in Siddhi

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiTestHelper.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation2TestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/managment/PlaybackTestCase.java

Add fixes for possible testcase failure

---

docs/documentation/siddhi-architecture.md

Fixing a few typos in the architecture documentation

Fix a few typos

---

README.md
docs/api/4.0.0.md
docs/api/4.0.9.md
docs/api/4.1.0.md
docs/api/4.1.46.md
docs/api/4.1.64.md
docs/api/4.1.7.md
docs/api/4.2.0.md
docs/api/4.2.20.md
docs/api/4.2.40.md
docs/api/4.3.0.md
docs/api/4.3.19.md
docs/api/4.4.0.md
docs/api/4.4.8.md
docs/api/5.0.0-m1.md
docs/api/5.0.0-m2.md
docs/api/latest.md
docs/documentation/siddhi-4.0.md
docs/documentation/siddhi-quckstart-4.0.md
docs/documentation/user-guide.md
docs/index.md
mkdocs.yml
modules/siddhi-doc-gen/src/main/java/io/siddhi/doc/gen/core/utils/Constants.java

> This PR updates the siddhi GitHub site URL as siddhi.io to avoid link failures due to site migration

Update siddhi site url as siddhi.io

---

docs/documentation/contribution.md
docs/documentation/siddhi-architecture.md
docs/documentation/user-guide.md

> This PR updates the Siddhi source code links in the documentation.

Update siddhi source code urls

---

modules/siddhi-core/src/test/java/io/siddhi/core/managment/AsyncTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/managment/PlaybackTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/sequence/absent/EveryAbsentSequenceTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/MultiClientDistributedSinkTestCase.java

Add possible fixes for test case failures

---

modules/siddhi-core/src/test/java/io/siddhi/core/TestUtil.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/absent/AbsentPatternTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/sequence/absent/AbsentSequenceTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/sequence/absent/LogicalAbsentSequenceTestCase.java

Add possible fixes for pattern/sequences test case failures

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/CollectionExpressionParser.java

> Explained in https://github.com/siddhi-io/siddhi/issues/1134 ..

Fix for not setting correct CollectionScope when streamId is not given

---

.travis.yml

Update travis with codecov integration changes

---

docs/api/latest.md
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalAggregationProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/config/SiddhiAppContext.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/ProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/OutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/StreamJunction.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/InputEventHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/Sink.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/output/sink/SinkMapper.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/Table.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/trigger/CronTrigger.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/trigger/PeriodicTrigger.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/trigger/StartTrigger.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/Scheduler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SiddhiAppParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/BufferedEventsTracker.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/MemoryUsageTracker.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/metrics/Level.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/metrics/SiddhiBufferedEventsMetric.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/metrics/SiddhiMemoryUsageMetric.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/window/Window.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/StatisticsTestCase.java

> $subject
> Give the ability to configure metrics using levels (off, basic, detail)
> The changed metrics level will be added to the Siddhi app context. All the elements which are calculates the metrics will check the siddhi app context's metrics level and element's given metric level and calculate the metrics

Add metrics Levels to Siddhi

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/statistics/BufferedEventsTracker.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/StatisticsTestCase.java

Fix statistics test case failures

---

modules/siddhi-core/pom.xml
modules/siddhi-query-api/pom.xml
modules/siddhi-query-compiler/pom.xml

Fix component level jacoco generation

---

README.md
coverage-reports/pom.xml
modules/siddhi-core/pom.xml
modules/siddhi-query-api/pom.xml
modules/siddhi-query-compiler/pom.xml
pom.xml

Add CodeCov badge to readme file

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/SelectorParser.java
pom.xml

Fix Variable copy issue at SelectorParser and fix check style issue

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/event/FirstGroupByPerEventOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/event/FirstPerEventOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/time/FirstGroupByPerTimeOutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/time/FirstPerTimeOutputRateLimiter.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/MinimumFunctionExtensionTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/ratelimit/EventOutputRateLimitTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/ratelimit/TimeOutputRateLimitTestCase.java

> Make it to output the first event as soon as it arrives.
> To use for event suppression logics

Fix behavior of "output first every"

---

README.md

Update readme with Siddhi Jenkins url

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/window/TimeLengthWindowTestCase.java

Add possible fix for intermittent test case failure

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java

Clean Metrics logs

---

modules/siddhi-core/pom.xml
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/window/TimeLengthWindowTestCase.java
modules/siddhi-query-api/pom.xml
modules/siddhi-query-compiler/pom.xml

Add possible fix for intermittent test case failure & pom refactoring

---

pom.xml

add maven source plugin so that source jars are generated when building

add maven source plugin to parent pom

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/QueryParser.java

> Fix IllegalStateException thrown at latency tracker MarkIn()

Fix IllegalStateException thrown at latency tracker MarkIn

---

docs/documentation/siddhi-5.x/query-guide-5.x.md
modules/siddhi-core/src/main/java/io/siddhi/core/query/output/ratelimit/OutputRateLimiter.java

> Improve source and error handling docs and fix IllegalStateException at latency tracker.

Improve docs and fix IllegalStateException at latency tracker 

---

modules/siddhi-core/pom.xml
modules/siddhi-query-api/pom.xml
modules/siddhi-query-compiler/pom.xml
pom.xml

> Update dependency versions and export ranges.

Update dependencies and minor version changes

---

docs/documentation/siddhi-5.x/query-guide-5.x.md

> Improve docs with more info and examples.

Improve fault stream, source and sink docs

---

docs/season-of-docs-2019.md

> Review proposal for Google Season of Docs.
> Did minor linguistic changes to the proposal for Google Season of Docs.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? esY
- Ran FindSecurityBugs plugin and verified report? Yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? Yes

Review proposal for Google Season of Docs.

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/InMemorySource.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/Source.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/InMemorySink.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/LogSink.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/Sink.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/distributed/DistributedTransport.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/MultiClientDistributedSink.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/SingleClientDistributedSink.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/TestFailingInMemorySink.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/TestFailingInMemorySink2.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/TestFailingInMemorySource.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/TestTrpInMemorySource.java

Introduce StateFactory Impl for source and Sink

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalExecutor.java

$subject to increase performance.
N/A
- Unit tests - Passes All
- Integration tests - N/A

Make table writes of aggregations async

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalExecutor.java

 Fix events missing in aggregation table writes

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/InMemorySink.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/LogSink.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/Sink.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/MultiClientDistributedSink.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/SingleClientDistributedSink.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/TestDepInMemorySink.java

Update method name in Sink interface

---

modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation1TestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation2TestCase.java

Prevent intermittent test failures due to aggregation write async change

---

modules/etc/feature.properties
modules/siddhi-core/pom.xml
modules/siddhi-feature/pom.xml
modules/siddhi-feature/resources/build.properties
modules/siddhi-samples/performance-samples/pom.xml
modules/siddhi-samples/pom.xml
modules/siddhi-samples/quick-start-samples/pom.xml
pom.xml

Add feature component to wrap Siddhi components

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/helper/DefinitionParserHelper.java

> Populate environment variable placeholders within annotations
> @sink(type='log', prefix='${ENV_TYPE}')
define stream TotalCountStream (totalCount long);

Add support to populate annotations with env variables

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalAggregationProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/ProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/OutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/StreamJunction.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/InputEventHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/trigger/CronTrigger.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/trigger/PeriodicTrigger.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/trigger/StartTrigger.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/Scheduler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/window/Window.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/StatisticsTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/InstanceOfFunctionTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/MaximumFunctionExtensionTestCase.java

> Improve issue finding capability.

Improve metrics reporting 

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/SiddhiAppRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalAggregationProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/ProcessStreamReceiver.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/output/ratelimit/OutputRateLimiter.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/StreamJunction.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/InputEventHandler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/trigger/CronTrigger.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/trigger/PeriodicTrigger.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/trigger/StartTrigger.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/Scheduler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/window/Window.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/StatisticsTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/InstanceOfFunctionTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/MaximumFunctionExtensionTestCase.java

Revert "Improve matrices reporting"

---

README.md

Update latest API Docs link

---

docs/documentation/siddhi-5.x/user-guide-5.x.md

> Added Siddhi as Kubernetes Micro Service Section

Added Using Siddhi as Kubernetes Micro Service Section

---

docs/documentation/siddhi-5.x/user-guide-5.x.md

>  Add doc section to view SiddhiProcess
> Add SiddhiProcess names that can be used along with kubectl commands.

 Add doc section to view SiddhiProcess

---

docs/documentation/siddhi-5.x/user-guide-5.x.md

> Add using Siddhi as Docker Micro Service user guide
> Guide users to run Siddhi as a micro service on Docker

Add using Siddhi as Docker Micro Service documentation

---

docs/documentation/siddhi-5.x/user-guide-5.x.md

> Add samples about following areas
- Deploy siddhi apps using config maps
- Enable/Disable ingress
- Enable HTTPS support

Add samples sub section for kubernetes section

---

docs/documentation/siddhi-5.x/query-guide-5.x.md

Remove redundant version info from aggregation docs

---

README.md
docs/download.md
docs/index.md

> Improve Siddhi site with docker tooling support.

Add docker tooling to siddhi site

---

docs/documentation/siddhi-5.x/user-guide-5.x.md

Update Siddhi operator installation files

---

docs/documentation/siddhi-5.x/user-guide-5.x.md

Update using Siddhi as Kubernetes micro service documentation

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/Aggregation1TestCase.java

Prevent intermittent test case failure

---

docs/documentation/siddhi-5.x/query-guide-5.x.md

>Add information on partition purging.

Add docs on partition purging.

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation1TestCase.java

1. $subject , 
Fixes, exceptions in Aggregation DB writes not being logged introduced by https://github.com/siddhi-io/siddhi/pull/1200 (Fix https://github.com/siddhi-io/siddhi/issues/1246)
2. Remove redundant checks
3. Prevent intermittent test failures
Log the exceptions thrown in Aggregation DB writes
Submit DB write tasks to Executor Service as execute
No performance loss was observed
N/A

Submit Aggregation db writes tasks to executorService through execute()

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalExecutor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StoreQueryParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/Aggregation1TestCase.java

Improve aggregation write log message & remove unnecessary store query log

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalExecutor.java

Fix checkstyle issue

---

docs/documentation/siddhi-5.x/user-guide-5.x.md

Update Siddhi Kubernetes user doc

---

docs/documentation/siddhi-5.x/user-guide-5.x.md

> Adding HTTPS logs and proper CURL command.
> minikube version: v0.33.1

 Added HTTPS logs and change secret creation

---

docs/extensions.md
modules/siddhi-core/siddhi-core-doc-gen/src/main/resources/gpl.docs.json
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation2TestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/aggregator/AndAggregatorExtensionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/aggregator/MaxAggregatorExtensionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/aggregator/MaxForeverAggregatorExtensionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/aggregator/MinForeverAggregatorExtensionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/aggregator/OrAggregatorExtensionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/function/FunctionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/function/MaximumFunctionExtensionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/function/MinimumFunctionExtensionTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/selector/attribute/aggregator/DistinctCountAttributeAggregatorExecutorTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/selector/attribute/aggregator/StdDevAttributeAggregatorExecutorTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/window/ExternalTimeBatchWindowTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/window/ExternalTimeWindowTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/window/LengthBatchWindowTestCase.java

Add test cases to siddhi-core-module

---

modules/siddhi-core/src/test/java/io/siddhi/core/query/FilterTestCase1.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/partition/PartitionTestCase1.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/DefineAggregationTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/DefineStreamTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/DefineTableTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/DefineTriggerTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/JoinQueryTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/PartitionQueryTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/PatternQueryTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/SimpleQueryTestCase.java
modules/siddhi-query-compiler/src/test/java/io/siddhi/query/test/SimpleQueryTestCase.java

Add testcases to siddhi-query-api module
- Unit tests 
> Code coverage information
> Details about the test cases and coverage
- Followed secure coding standards …

Add testcases to siddhi-query-api module

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/source/SourceHandlerManager.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/helper/DefinitionParserHelper.java

> $subject
> Handle events with respect to the source type

Add source type information to source handler

---

modules/siddhi-core/src/test/java/io/siddhi/core/query/partition/PartitionTestCase1.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/DefineTableTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/PatternQueryTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/SimpleQueryTestCase.java

Remove unnecessary lines in testcase
- Unit tests 
> Code coverage information
> Details about the test cases and coverage
- Followed secure coding standards in …

Remove unnecessary lines in testcase

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/RecreateInMemoryData.java

$subject
N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

Fix not propagating records when Executor changes to processing mode

---

docs/documentation/siddhi-4.x/query-guide-4.x.md
docs/documentation/siddhi-5.x/query-guide-5.x.md

Fix archetype creation docs

---

docs/documentation/siddhi-5.x/user-guide-5.x.md

> Add more relevant information

update docker hub info

---

modules/siddhi-core/src/main/java/io/siddhi/core/table/record/AbstractQueryableRecordTable.java

In HA mode fix issue in store query execution

Fix store query execution in HA mode

---

modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/CountPreStateProcessor.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/CountPatternTestCase.java

> Make the count bases patterns to work as expected. 
> Fix issue https://github.com/siddhi-io/siddhi/issues/1201
> Checking for the event expiry. 
> Fix bug on the timely removal of outdated count pattern events

Timely removal of outdated count pattern events

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalAggregationProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/RecreateInMemoryData.java

[Aggregation] Clear all executors at one go before refreshing executors

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalAggregationProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/RecreateInMemoryData.java

Aggregation] Clear all executors at one go before refreshing executors

---

docs/documentation/siddhi-5.x/config-guide-5.x.md

Add configuring metrics section

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationExpressionVisitor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/AggregationParser.java

$subject, on conditions, are passed to DB for all attributes not only group by
N/A

Optimise on condition for all table attributes for aggregations

---

docs/documentation/siddhi-5.x/architecture-5.x.md

Correct spelling in architecture-5.x.md

---

docs/documentation/siddhi-5.x/siddhi-as-a-kubernetes-microservice-5.x.md

Update Siddhi Operator version in Siddhi documentation

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/event/stream/StreamEvent.java

Add fix for https://github.com/siddhi-io/siddhi/issues/1238

---

README.md

Update Siddhi user guide links due to recent doc refactoring

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/IncrementalAggregationProcessor.java

Synchronise initialising aggregation executors

---

modules/siddhi-core/src/main/java/io/siddhi/core/event/ComplexEventChunk.java
modules/siddhi-core/src/test/java/io/siddhi/core/stream/event/ComplexEventChunkTestCase.java

Fix dead cpu loop in ComplexEventChunk.getLastEvent

Fix dead cpu loop in getLastEvent

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/BaseIncrementalValueStore.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalAggregationProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalDataAggregator.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalDataPurger.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutorsInitialiser.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/OutOfOrderEventsDataAggregator.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiConstants.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation1TestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation2TestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/AggregationFilterTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/AggregationFindQueryValidationTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/DistinctCountAggregationTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/LatestAggregationTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/PurgingTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

 Refactor Aggregation classes and test cases

---

docs/documentation/siddhi-5.x/query-guide-5.x.md

> Update docs for window, event type, aggregation, group by, having, and order by

Improve Siddhi Query Guide

---

coverage-reports/pom.xml
modules/siddhi-annotations/pom.xml
modules/siddhi-core/pom.xml
modules/siddhi-doc-gen/pom.xml
modules/siddhi-query-api/pom.xml
modules/siddhi-query-compiler/pom.xml
modules/siddhi-samples/performance-samples/pom.xml
modules/siddhi-samples/pom.xml
modules/siddhi-samples/quick-start-samples/pom.xml
modules/siddhi-service/pom.xml
pom.xml

> To rename the 4.x branch version

Merge 4.4.x to 4.x.x to remove 4.4.x branch. 

---

docs/api/4.5.0.md
docs/api/4.5.10.md
docs/api/4.5.11.md
docs/api/4.5.9.md
docs/index.md
mkdocs.yml
modules/siddhi-doc-gen/src/main/java/io/siddhi/doc/gen/core/utils/DocumentationUtils.java
modules/siddhi-doc-gen/src/main/java/io/siddhi/doc/gen/metadata/ExtensionMetaData.java
modules/siddhi-doc-gen/src/main/java/io/siddhi/doc/gen/metadata/ParameterOverloadMetaData.java
modules/siddhi-doc-gen/src/main/resources/templates/documentation.md.ftl

> Improve doc gen and add 4.x APIs

 Improve doc gen to include parameter overload and add API versions 4.5.10, 4.5.11, and 4.5.9

---

docs/api/latest.md
docs/stylesheets/extra.css
modules/siddhi-doc-gen/pom.xml
modules/siddhi-doc-gen/src/main/java/io/siddhi/doc/gen/core/MarkdownDocumentationGenerationMojo.java
modules/siddhi-doc-gen/src/main/java/io/siddhi/doc/gen/core/MkdocsGitHubPagesDeployMojo.java
modules/siddhi-doc-gen/src/main/java/io/siddhi/doc/gen/core/utils/DocumentationUtils.java
modules/siddhi-doc-gen/src/main/java/io/siddhi/doc/gen/metadata/ExtensionMetaData.java
modules/siddhi-doc-gen/src/main/resources/templates/documentation.md.ftl

> Improve auto generated documentation

Improve doc gen plugin to support origin jar info data

---

docs/documentation/siddhi-5.x/query-guide-5.x.md

> add cache query examples with explanations. Explain cache parameters and behavior.

Add cache section to 5.x.x query guide

---

mkdocs.yml

Fix link in Docs

---

modules/siddhi-query-api/src/main/java/io/siddhi/query/api/definition/TableDefinition.java

> Performance Improvement for Table Definition Attribute Array Name list.
Optimizing the getAttributeNameArray() by overriding the base implementation to remove hotstop on this method.
This method from the base implementation is called on every event occurrence where it iterates the attribute list. Optimizing this method to compute the attribute list only once when the stream definition changes and not on every call.

 Performance Improvement for Table Definition Attribute Array Name list retrieval 

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/AggregateWindowProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/incremental/AvgIncrementalAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/incremental/CountIncrementalAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/incremental/DistinctCountIncrementalAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/incremental/IncrementalAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/incremental/MaxIncrementalAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/incremental/MinIncrementalAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/selector/attribute/aggregator/incremental/SumIncrementalAttributeAggregator.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/Table.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/InputStreamParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/JoinInputStreamParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/QueryParser.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/StoreQueryParser.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/Aggregation2TestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/LatestAggregationTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/aggregation/SelectOptimisationAggregationTestCase.java
modules/siddhi-core/src/test/resources/testng.xml

Optimize table lookups of aggregation querying, as of now, 
```
select * 
from stockAggregation_MINUTES 
where AGG_TIMESTAMP >=t1 and AGG_TIMESTAMP<=t2 
```
is used. This can be optimised.
Ported based on https://github.com/siddhi-io/siddhi/pull/1339
Optimize the above query so as to pick only the needed records.
For aggregation, 
```
define aggregation stockAggregation 
from stockStream 
select symbol, count() as count 
group by symbol 
aggregate by timestamp every sec, min;
```
and following query,
```
from stockAggregation 
within 1496200000000L, 1596434876000L 
per \"seconds\" 
select symbol, sum(count) as count 
group by s.symbol 
```
This can be transformed as SQL query, 
```
select max(AGG_TIMESTAMP), symbol, sum(AGG_COUNT) as AGG_COUNT
from stockAggregation_MINUTES 
where …
```

[4.x.x] Aggregation select optimisation

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/Table.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/collection/operator/IncrementalAggregateCompileCondition.java

$subject
Fix https://github.com/siddhi-io/siddhi/issues/1379
Ported from https://github.com/siddhi-io/siddhi/pull/1380
N/A

[4.x.x] Fix log rolling when trying to reconnect when aggregation join query is run

---

modules/siddhi-core/src/main/java/io/siddhi/core/query/selector/attribute/aggregator/incremental/AvgIncrementalAttributeAggregator.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/selector/attribute/aggregator/incremental/CountIncrementalAttributeAggregator.java

$subject, Fix https://github.com/siddhi-io/siddhi/issues/927
N/A

Add warn log for use of count(attributeName)

---

modules/siddhi-core/src/main/java/io/siddhi/core/table/record/AbstractQueryableRecordTable.java
modules/siddhi-core/src/main/java/io/siddhi/core/table/record/AbstractRecordTable.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/util/TestStore.java

Add code refactoring changes to avoid API changes for event store impls

---

README.md
docs/index.md
modules/siddhi-core/src/main/java/io/siddhi/core/executor/function/FunctionExecutor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/AbsentLogicalPreStateProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/CountPreStateProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/LogicalPreStateProcessor.java
modules/siddhi-core/src/main/java/io/siddhi/core/query/input/stream/state/StreamPreStateProcessor.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/CountPatternTestCase.java

Fix Siddhi Pattern not working with `every` and `<>` (count), and fix regression issue on a pattern that causes concurrent modification exception.

Fix #1385 Siddhi Pattern does not work with Occurrences.

---

modules/siddhi-core/src/main/java/io/siddhi/core/table/record/AbstractQueryableRecordTable.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/cache/CacheExpirer.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/cache/CacheExpiryAndReloadTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/cache/CacheLFUTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/cache/CacheLRUTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/table/cache/QueryAPITestCaseForTableWithCache.java
modules/siddhi-core/src/test/resources/log4j.properties
modules/siddhi-core/src/test/resources/testng.xml

> Cache test cases should run in maven build

add cache test case classes to testng

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/extension/validator/InputParameterValidator.java

> Fix Fix no-arg functions are not properly validated #1401 
> to improve auto validation

Fix no-arg functions are not properly validated #1401

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/StreamJunction.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/holder/IndexEventHolder.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/InstanceOfFunctionTestCase.java
modules/siddhi-core/src/test/java/org/wso2/siddhi/core/query/function/MaximumFunctionExtensionTestCase.java

> Make sure the error handler assigned is used in the StreamJunction and in the tables.

Siddhi Error Handlers not getting engaged #1414

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/stream/FaultStreamTestCase.java

Add testcase to catch exceptions registering a exception listener

---

modules/siddhi-core/src/test/java/io/siddhi/core/managment/AsyncTestCase.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/SiddhiApp.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/definition/AbstractDefinition.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/definition/AggregationDefinition.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/definition/StreamDefinition.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/definition/TableDefinition.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/execution/query/input/stream/AnonymousInputStream.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/expression/Variable.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/expression/condition/And.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/expression/condition/In.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/expression/condition/Not.java
modules/siddhi-query-api/src/main/java/io/siddhi/query/api/expression/condition/Or.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/DefineAggregationTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/DefineFunctionTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/DefineStreamTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/JoinQueryTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/PartitionQueryTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/PatternQueryTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/RetrieveMessageContextTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/SimpleQueryTestCase.java
modules/siddhi-query-api/src/test/java/io/siddhi/query/api/TableQueryTestCase.java
modules/siddhi-query-api/src/test/resources/testng.xml
modules/siddhi-query-compiler/src/test/java/io/siddhi/query/test/SimpleQueryTestCase.java

Improve query api code coverage 

---

modules/siddhi-core/src/main/java/io/siddhi/core/SiddhiManager.java
modules/siddhi-core/src/main/java/io/siddhi/core/config/SiddhiAppContext.java
modules/siddhi-core/src/main/java/io/siddhi/core/config/SiddhiContext.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/distributed/DistributedTransport.java

Fix java doc errors

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/SinkMapper.java

Improve TemplateBuilder to allow extended logic

---

pom.xml

make log4j version range compatible with pax-logging

make log4j version range compatible with pax-logging

---

modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/LatestAggregationTestCase.java

Prevent intermittent test case failures

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java

> Fix ConcurrentModificationExceptions when state persistence interval is low
> Fix issues when state persistence interval is low
> Allow concurrent modifications by chaning HashMap tp ConcurrentHashMap

Fix ConcurrentModificationExceptions when state persistence interval is low

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/transport/TemplateBuilder.java

Fix for incorrect formatting of integers when using JSON, XML & Text custom mapping

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/Source.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/source/SourceMapper.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/transport/TemplateBuilder.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/InMemoryTransportTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/TestSinkOptionSinkMapper.java
modules/siddhi-core/src/test/java/io/siddhi/core/transport/TestSourceOptionSourceMapper.java

Purpose
> Add support for source type and source options from SourceMapper, Fixes: #1470
> Allow Template builder to expose type.
> #1470 Add support for source type and source options from SourceMapper and Allow Template builder to expose type.

Add support for source type and source options from SourceMapper and Allow Template builder to expose type.

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/table/record/ExpressionBuilder.java

Fix https://github.com/wso2/product-sp/issues/1039

Fix NPE when count() AttributeFunction is used

---

pom.xml

update hazelcast.version in siddhi

update hazelcast.version in siddhi

---

modules/siddhi-core/src/test/java/io/siddhi/core/query/sequence/SequenceTestCase.java

Test case to find peaks with sequence query

---

README.md

Update readme with contribution links

---

modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/absent/LogicalAbsentPatternTestCase.java

Reduce the probability of the test failure

---

modules/siddhi-core/src/test/java/io/siddhi/core/query/pattern/absent/LogicalAbsentPatternTestCase.java
modules/siddhi-core/src/test/java/io/siddhi/core/query/window/CronWindowTestCase.java

Reduce the probability of test failure

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiManagerComponent.java

Avoid maintaining multiple extension map at SiddhiExtensionLoader

---

modules/siddhi-core/src/main/java/io/siddhi/core/SiddhiAppRuntimeImpl.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/InputHandler.java
modules/siddhi-core/src/main/java/io/siddhi/core/stream/input/InputManager.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation1TestCase.java

Fix input handler being silent when siddhi app is not running

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/BaseIncrementalValueStore.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalDataAggregator.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/OutOfOrderEventsDataAggregator.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/OnDemandQueryParser.java

Add proper synchronization to BaseIncrementalValueStore class

---

modules/siddhi-core/src/main/java/io/siddhi/core/SiddhiManager.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/SiddhiExtensionLoader.java

Improve logs for duplicate extension additions

---

modules/siddhi-query-compiler/src/main/java/io/siddhi/query/compiler/SiddhiCompiler.java

Improve error with context when updating environment variable

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/AggregationFilterTestCase.java

Fix aggregation optimisation inconsistent behaviour

---

modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/Aggregation1TestCase.java

Prevent intermittent test failures

---

modules/siddhi-query-compiler/src/main/antlr4/io/siddhi/query/compiler/SiddhiQL.g4

Resolve #1549 caused by typos in SiddhiQL.g4 grammar file.

Fix issue in siddhi-query-compiler/SiddhiQL.g4 grammar file

---

README.md

Add Cli best practices badge to readme

---

README.md

> There has a small problem at readme.md file,a word "can" appeared twice at head of line.
> Delete the unnecessary word "can"

Delete unnecessary word "can" at the readme.md file

---

modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/SelectOptimisationAggregationTestCase.java

Add test case for aggregation group by

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/Sink.java

Print stacktrace while dropping the event at Sink

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/Sink.java

Print stacktrace while dropping the event at Sink iff debug enabled

---

modules/siddhi-core/src/main/java/io/siddhi/core/table/Table.java

Add default value to errorAction

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/input/stream/single/EntryValveProcessor.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/stream/input/InputEntryValve.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/Scheduler.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/ThreadBarrier.java
modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/snapshot/SnapshotService.java

This PR fixes a `ConcurrentModificationException` when taking snapshots under a load test.

Fix for ConcurrentModificationException of snapshot

---

modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/SelectOptimisationAggregationTestCase.java

Fix build Change test case aggregation to be based on external timestamp

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/query/processor/stream/window/UniqueExternalTimeBatchWindowProcessor.java

Resolves https://github.com/siddhi-io/siddhi/issues/1502
Cannot do as this was never reproduced.

Fix NPE observed in uniqueExternalTimeBatch

---

modules/siddhi-core/src/test/java/io/siddhi/core/query/trigger/TriggerTestCase.java

Fix testcase failure

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/persistedaggregation/CudStreamProcessorQueueManager.java

Add debug logs to make debug easier

Add debug logs

---

modules/siddhi-core/src/main/resources/db-aggregation-config.xml

> Fixes https://github.com/wso2/product-is/issues/12156

Fix the persisted aggregation SQL query.

---

modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java
modules/siddhi-core/src/main/resources/db-aggregation-config.xml

> Resolves https://github.com/wso2/product-is/issues/12416

Primary key violation during persisted aggregation fixed.

---

modules/siddhi-core/src/main/java/io/siddhi/core/stream/output/sink/Sink.java

Resolves https://github.com/siddhi-io/siddhi/issues/1754

Fix reconnecting for Error Store

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutorsInitialiser.java

Improve state recreation

---

modules/siddhi-extensions/event-table/pom.xml
pom.xml

add log4j1 as test dependency

---

appveyor.yml
modules/siddhi-core/pom.xml
modules/siddhi-feature/pom.xml
pom.xml

> Bump versions of external dependencies

Bump versions of external dependencies

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutorsInitialiser.java

Fixes https://github.com/wso2/api-manager/issues/17

Fix issue with persisted aggregations

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalDataPurger.java
modules/siddhi-core/src/test/java/io/siddhi/core/aggregation/PurgingTestCase.java

Fixes https://github.com/wso2/api-manager/issues/411
This fix should be backported to wso2am-analytics 2.6.0, 3.0.0, and 3.1.0.

Change AGG_START_TIMESTAMP_COL usages to purgingTimestampField variable

---

.travis.yml
appveyor.yml

> $subject
- https://github.com/siddhi-io/siddhi/pull/1785

Update travis and appveyor to openjdk11

---

modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/IncrementalExecutorsInitialiser.java
modules/siddhi-core/src/main/java/io/siddhi/core/util/parser/AggregationParser.java

From AggregationRuntime to IncrementalExecutorsInitialiser
Purpose: Fix the https://github.com/wso2/api-manager/issues/561

Move the log entries of initialiseExecutors

---

pom.xml

Update Gson version

---

pom.xml

Add docLint none configuration to javadoc plugin

---

modules/siddhi-core/pom.xml
pom.xml

- $subject to the latest quartz orbit bundle 2.3.2.wso2v1[1]
[1] https://github.com/wso2/orbit/tree/master/quartz/2.3.2.wso2v1

Update quartz dependency in siddhi-core

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PersistenceTestCase.java

> Close siddhiManager after the test case

Close siddhiManager after the test case

---

modules/siddhi-core/src/test/java/org/wso2/siddhi/core/managment/PersistenceTestCase.java

> Increase sleep time to avoid test failure

Increase sleep time to avoid test failure

---

pom.xml

$title
n/a
n/a
n/a
n/a
- Unit tests 
> Code coverage information
> Details about the test cases and coverage
n/a
n/a
JDK 11, ANTLR v4.11.1

Bump ANTLR version to v4.11.1

---

modules/siddhi-core/src/main/java/io/siddhi/core/SiddhiAppRuntimeImpl.java
modules/siddhi-core/src/main/java/io/siddhi/core/aggregation/AggregationRuntime.java

- fixes: https://github.com/wso2/api-manager/issues/2305

Add getters to the variables

---

modules/siddhi-doc-gen/pom.xml
pom.xml

Fix commons-io groupId

---

modules/siddhi-core/src/test/resources/testng.xml

Comment FaultStreamTestCase due to intermittent test failure

Comment FaultStreamTestCase due to intermittent test failure

---

modules/siddhi-core/src/main/java/org/wso2/siddhi/core/util/parser/ExecutionPlanParser.java

Fixes https://github.com/wso2/api-manager/issues/3780

Set clean interval using a system property

---

modules/siddhi-extensions/eval-script/src/main/java/org/wso2/siddhi/extension/evalscript/EvalJavaScript.java

Blocks all java invocations via siddi apps
Used `--no-java` option when creating the script engine

Update javascript engine to block java invocations
